schema_version: 1

context:
  name: openfisca-country-template
  version: 7.1.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/openfisca_country_template-${{ version }}.tar.gz
  sha256: 57371d284e7d1f6850e00e8b348f1a396cf480b007afcab0d4b306d4f1a1bb2f

build:
  number: 2
  noarch: python
  script: pip install . -v --no-deps

requirements:
  host:
  - numpy
  - pip
  - python
  - setuptools >=61.0
  run:
  - numpy
  - python
  - openfisca-core >=42

about:
  summary: OpenFisca Rules as Code model for Country-Template.
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
  - bonjourmauko
