schema_version: 1

context:
  name: pylint-per-file-ignores
  version: 1.3.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylint_per_file_ignores-${{ version }}.tar.gz
  sha256: 3c641f69c316770749a8a353556504dae7469541cdaef38e195fe2228841451e

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
  - python
  - poetry-core >=1.0.0
  - pip
  run:
  - pylint >=3.3.1,<4.0
  - python
  - tomli >=2.0.1,<3.0.0

tests:
- python:
    imports:
    - pylint_per_file_ignores
- requirements:
    run:
    - pip
  script:
  - pip check

about:
  summary: A pylint plugin to ignore error codes per file.
  license: MIT
  homepage: https://github.com/christopherpickering/pylint-per-file-ignores.git

extra:
  recipe-maintainers:
  - bonjourmauko
