[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenFisca-Core"
version = "47.0.0"
description = "A versatile microsimulation free software"
readme = "README.md"
authors = [
  {name = "OpenFisca Team", email = "contact@openfisca.org"},
]
requires-python = ">=3.11"
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Operating System :: POSIX",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ]
keywords = ["benefit", "microsimulation", "social", "tax"]
# Please make sure to cap all dependency versions, in order to avoid unwanted
# functional and integration breaks caused by external code updates.
# DO NOT add space between '>=' and version number as it break conda build.
dependencies = [
    "PyYAML >=6.0.1, <7.0",
    # https://github.com/yaml/pyyaml/pull/808
    "PyYAML >=6.0.2, <7.0 ; python_version >= \"3.13\"",
    "StrEnum >=0.4.8, <0.5.0",
    "dpath >=2.2.0, <3.0",
    "numexpr >=2.10.1, <3.0",
    # https://numpy.org/neps/nep-0029-deprecation_policy.html
    "numpy >=1.25, <=3 ; python_version >= \"3.11\"",
    "numpy >=1.26, <=3 ; python_version >= \"3.12\"",
    # https://numpy.org/devdocs/release/2.1.0-notes.html
    "numpy >=2.1, <=3 ; python_version >= \"3.13\"",
    "pendulum >=3.0.0, <4.0.0",
    "psutil >=5.9.4, <6.0",
    "pytest >=8.3.3, <9.0",
    "sortedcontainers >=2.4.0, <3.0",
    "typing_extensions >=4.16.0, <5.0",
]

license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]

[dependency-groups]
dev = [
    "codespell >=2.3.0, <3.0",
    "colorama >=0.4.4, <0.5",
    "darglint >=1.8.1, <2.0",
    "docutils >=0.23",
    "idna >=3.10, <4.0",
    "isort >=5.13.2, <6.0",
    "mypy >=1.11.2, <2.0",
    "pyright >=1.1.382, <2.0",
    "ruff >=0.16.7",
    "OpenFisca-Core[ci]",
    "twine >1",
]

[project.scripts]
openfisca = "openfisca_core.scripts.openfisca_command:main"
openfisca-run-test = "openfisca_core.scripts.openfisca_command:main"

[project.urls]
Homepage = "https://github.com/openfisca/openfisca-core"
Documentation = "https://openfisca.org/doc/"
Repository = "https://github.com/openfisca/openfisca-core.git"

[project.optional-dependencies]
web-api = [
    "Flask >=2.2.3, <4.0",
    "Flask-Cors >=3.0.10, <4.0",
    "gunicorn >=21.0, <22.0",
    "Werkzeug >=2.2.3, <4.0",
]

ci = [
    "openapi-spec-validator >=0.7.1, <0.8.0",
    "OpenFisca-Core[web-api]",
    "openfisca-country-template >=8, <9",
    "openfisca-extension-template >=2.0.7, <3",
]

[tool.codespell]
ignore-words-list = [
    "THIRDPARTY",
    "ans",
    "constitue",
    "exemple",
    "fonction",
    "impot",
    "treshold",
]
skip = [
"*.egg-info",
"./venv",
]

[tool.mypy]
check_untyped_defs = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_expr = false
disallow_any_unimported = false
follow_imports = "skip"
ignore_missing_imports = true
implicit_reexport = false
install_types = true
mypy_path = "stubs"
non_interactive = true
plugins = "numpy.typing.mypy_plugin"
pretty = true
python_version = 3.10
strict = false
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "openfisca_core.*.tests.*"
ignore_errors = true

[tool.pytest]
addopts = ["--disable-pytest-warnings", "--doctest-modules", "--showlocals"]
doctest_optionflags = ["ELLIPSIS", "IGNORE_EXCEPTION_DETAIL", "NUMBER", "NORMALIZE_WHITESPACE"]
python_files = "**/*.py"
testpaths = "tests"

[tool.ruff.lint]
ignore = [
    "BLE001",
    "TRY004",
    "TRY002",
    "RUF012",
    "PLW1510",
    "PLC0105",
    "DTZ007",
    "B019",
    "DTZ012",
    "S102",
]

[tool.setuptools.packages.find]
exclude = ["tests*"]

[tool.uv.sources]
#openfisca-country-template = { path = "../country-template", editable = true }
openfisca-country-template = { git = "https://github.com/openfisca/country-template.git", branch = "more_relationships" }
