package:
  name: "openfisca-core"
  version: "0.0.1"

source:
  url: https://pypi.io/packages/source/O/OpenFisca-Core/OpenFisca-Core-35.7.5.tar.gz
  #path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  # script: python setup.py install

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.6
    - dpath ==2.0.5
    - nptyping ==1.4.4
    - numexpr >=2.7.0,<=3.0
    - numpy >=1.11,<1.21
    - psutil >=5.4.7,<6.0.0
    - pytest >=4.4.1,<6.0.0  # For openfisca test
    - PyYAML >=3.10
    - sortedcontainers ==2.2.2
    - typing-extensions ==3.10.0.2

about:
  home: https://openfisca.org
  license: AGPL-3.0
  license_file: LICENSE
  summary: "A versatile microsimulation free software"


