# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Tue Feb 21 11:40:23 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenFisca", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/OpenFisca22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.file_menu = QtGui.QMenu(self.menubar)
        self.file_menu.setTitle(QtGui.QApplication.translate("MainWindow", "&Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setIconSize(QtCore.QSize(22, 22))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actFileQuit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/process-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFileQuit.setIcon(icon1)
        self.actFileQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actFileQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actFileQuit.setObjectName(_fromUtf8("actFileQuit"))
        self.actFileRefresh = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFileRefresh.setIcon(icon2)
        self.actFileRefresh.setText(QtGui.QApplication.translate("MainWindow", "&Calculer", None, QtGui.QApplication.UnicodeUTF8))
        self.actFileRefresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Calculer (F9)", None, QtGui.QApplication.UnicodeUTF8))
        self.actFileRefresh.setShortcut(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.actFileRefresh.setObjectName(_fromUtf8("actFileRefresh"))
        self.actPreferences = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/preferences-desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPreferences.setIcon(icon3)
        self.actPreferences.setText(QtGui.QApplication.translate("MainWindow", "Préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.actPreferences.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actPreferences.setObjectName(_fromUtf8("actPreferences"))
        self.actExportCsv = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-save csv.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actExportCsv.setIcon(icon4)
        self.actExportCsv.setText(QtGui.QApplication.translate("MainWindow", "Exporter la table", None, QtGui.QApplication.UnicodeUTF8))
        self.actExportCsv.setToolTip(QtGui.QApplication.translate("MainWindow", "Exporter la table", None, QtGui.QApplication.UnicodeUTF8))
        self.actExportCsv.setObjectName(_fromUtf8("actExportCsv"))
        self.actExportPng = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/document-save png.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actExportPng.setIcon(icon5)
        self.actExportPng.setText(QtGui.QApplication.translate("MainWindow", "Exporter le graphique", None, QtGui.QApplication.UnicodeUTF8))
        self.actExportPng.setToolTip(QtGui.QApplication.translate("MainWindow", "Exporter le graphique", None, QtGui.QApplication.UnicodeUTF8))
        self.actExportPng.setObjectName(_fromUtf8("actExportPng"))
        self.actModeReforme = QtGui.QAction(MainWindow)
        self.actModeReforme.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/comparison22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actModeReforme.setIcon(icon6)
        self.actModeReforme.setText(QtGui.QApplication.translate("MainWindow", "Réforme", None, QtGui.QApplication.UnicodeUTF8))
        self.actModeReforme.setToolTip(QtGui.QApplication.translate("MainWindow", "Différence entre la situation simulée et la situation actuelle", None, QtGui.QApplication.UnicodeUTF8))
        self.actModeReforme.setObjectName(_fromUtf8("actModeReforme"))
        self.actCasType = QtGui.QAction(MainWindow)
        self.actCasType.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/castype22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCasType.setIcon(icon7)
        self.actCasType.setText(QtGui.QApplication.translate("MainWindow", "Cas type", None, QtGui.QApplication.UnicodeUTF8))
        self.actCasType.setToolTip(QtGui.QApplication.translate("MainWindow", "Mode cas type", None, QtGui.QApplication.UnicodeUTF8))
        self.actCasType.setObjectName(_fromUtf8("actCasType"))
        self.actBareme = QtGui.QAction(MainWindow)
        self.actBareme.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bareme22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actBareme.setIcon(icon8)
        self.actBareme.setText(QtGui.QApplication.translate("MainWindow", "Barème", None, QtGui.QApplication.UnicodeUTF8))
        self.actBareme.setToolTip(QtGui.QApplication.translate("MainWindow", "Mode Barème", None, QtGui.QApplication.UnicodeUTF8))
        self.actBareme.setObjectName(_fromUtf8("actBareme"))
        self.file_menu.addAction(self.actExportCsv)
        self.file_menu.addAction(self.actExportPng)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.actPreferences)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.actFileQuit)
        self.menuSimulation.addAction(self.actFileRefresh)
        self.menuSimulation.addSeparator()
        self.menuSimulation.addAction(self.actCasType)
        self.menuSimulation.addAction(self.actBareme)
        self.menuSimulation.addSeparator()
        self.menuSimulation.addAction(self.actModeReforme)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.toolBar.addAction(self.actExportCsv)
        self.toolBar.addAction(self.actExportPng)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actFileRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actCasType)
        self.toolBar.addAction(self.actBareme)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actModeReforme)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actPreferences)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

import resources_rc
