# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page_isf.ui'
#
# Created: Wed May 23 18:30:47 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Page_isf(object):
    def setupUi(self, Page_isf):
        Page_isf.setObjectName(_fromUtf8("Page_isf"))
        Page_isf.resize(730, 557)
        Page_isf.setMinimumSize(QtCore.QSize(730, 0))
        Page_isf.setMaximumSize(QtCore.QSize(730, 16777215))
        Page_isf.setWindowTitle(QtGui.QApplication.translate("Page_isf", "Form", None, QtGui.QApplication.UnicodeUTF8))
        Page_isf.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(Page_isf)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(Page_isf)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setText(QtGui.QApplication.translate("Page_isf", "1| ACTIF BRUT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_60 = QtGui.QLabel(Page_isf)
        self.label_60.setStyleSheet(_fromUtf8(""))
        self.label_60.setText(QtGui.QApplication.translate("Page_isf", "IMMEUBLES BÂTIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_65 = QtGui.QLabel(Page_isf)
        self.label_65.setStyleSheet(_fromUtf8(""))
        self.label_65.setText(QtGui.QApplication.translate("Page_isf", "Résidence principale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout.addWidget(self.label_65, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.label_62 = QtGui.QLabel(Page_isf)
        self.label_62.setMinimumSize(QtCore.QSize(30, 20))
        self.label_62.setMaximumSize(QtCore.QSize(30, 20))
        self.label_62.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_62.setStyleSheet(_fromUtf8(""))
        self.label_62.setText(QtGui.QApplication.translate("Page_isf", "1AB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout.addWidget(self.label_62, 1, 2, 1, 1)
        self.b1ab = QtGui.QSpinBox(Page_isf)
        self.b1ab.setEnabled(True)
        self.b1ab.setMinimumSize(QtCore.QSize(60, 20))
        self.b1ab.setMaximumSize(QtCore.QSize(60, 20))
        self.b1ab.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1ab.setWrapping(False)
        self.b1ab.setFrame(True)
        self.b1ab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1ab.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1ab.setAccelerated(False)
        self.b1ab.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1ab.setKeyboardTracking(True)
        self.b1ab.setSuffix(_fromUtf8(""))
        self.b1ab.setPrefix(_fromUtf8(""))
        self.b1ab.setMinimum(0)
        self.b1ab.setMaximum(99999999)
        self.b1ab.setSingleStep(10000)
        self.b1ab.setProperty("value", 0)
        self.b1ab.setObjectName(_fromUtf8("b1ab"))
        self.gridLayout.addWidget(self.b1ab, 1, 3, 1, 1)
        self.label_66 = QtGui.QLabel(Page_isf)
        self.label_66.setStyleSheet(_fromUtf8(""))
        self.label_66.setText(QtGui.QApplication.translate("Page_isf", "Autres immeubles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout.addWidget(self.label_66, 2, 0, 1, 2)
        self.label_63 = QtGui.QLabel(Page_isf)
        self.label_63.setMinimumSize(QtCore.QSize(30, 20))
        self.label_63.setMaximumSize(QtCore.QSize(30, 20))
        self.label_63.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_63.setStyleSheet(_fromUtf8(""))
        self.label_63.setText(QtGui.QApplication.translate("Page_isf", "1AC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout.addWidget(self.label_63, 2, 2, 1, 1)
        self.b1ac = QtGui.QSpinBox(Page_isf)
        self.b1ac.setEnabled(True)
        self.b1ac.setMinimumSize(QtCore.QSize(60, 20))
        self.b1ac.setMaximumSize(QtCore.QSize(60, 20))
        self.b1ac.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1ac.setWrapping(False)
        self.b1ac.setFrame(True)
        self.b1ac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1ac.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1ac.setAccelerated(False)
        self.b1ac.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1ac.setKeyboardTracking(True)
        self.b1ac.setSuffix(_fromUtf8(""))
        self.b1ac.setPrefix(_fromUtf8(""))
        self.b1ac.setMinimum(0)
        self.b1ac.setMaximum(99999999)
        self.b1ac.setSingleStep(10000)
        self.b1ac.setProperty("value", 0)
        self.b1ac.setObjectName(_fromUtf8("b1ac"))
        self.gridLayout.addWidget(self.b1ac, 2, 3, 1, 1)
        self.label_79 = QtGui.QLabel(Page_isf)
        self.label_79.setMinimumSize(QtCore.QSize(41, 20))
        self.label_79.setMaximumSize(QtCore.QSize(41, 20))
        self.label_79.setText(QtGui.QApplication.translate("Page_isf", "cochez", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte02", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout.addWidget(self.label_79, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_61 = QtGui.QLabel(Page_isf)
        self.label_61.setStyleSheet(_fromUtf8(""))
        self.label_61.setText(QtGui.QApplication.translate("Page_isf", "IMMEUBLES NON BÂTIS, PARTS DE GROUPEMENTS FORESTIERS OU FONCIERS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.verticalLayout.addWidget(self.label_61)
        self.label_3 = QtGui.QLabel(Page_isf)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setText(QtGui.QApplication.translate("Page_isf", "2| PASSIF, AUTRES DEDUCTIONS ET REDUCTIONS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(Page_isf)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setText(QtGui.QApplication.translate("Page_isf", "4| IMPUTATION DE L\'IMPOT SUR LA FORTUNE ACQUITTE HORS DE FRANCE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Page_isf)
        QtCore.QMetaObject.connectSlotsByName(Page_isf)

    def retranslateUi(self, Page_isf):
        pass

