# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page_isf.ui'
#
# Created: Tue Nov 27 17:24:32 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Page_isf(object):
    def setupUi(self, Page_isf):
        Page_isf.setObjectName(_fromUtf8("Page_isf"))
        Page_isf.resize(730, 797)
        Page_isf.setMinimumSize(QtCore.QSize(730, 0))
        Page_isf.setMaximumSize(QtCore.QSize(730, 16777215))
        Page_isf.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(Page_isf)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(Page_isf)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_60 = QtGui.QLabel(Page_isf)
        self.label_60.setStyleSheet(_fromUtf8(""))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 0, 0, 1, 1)
        self.label_65 = QtGui.QLabel(Page_isf)
        self.label_65.setStyleSheet(_fromUtf8(""))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout.addWidget(self.label_65, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.label_62 = QtGui.QLabel(Page_isf)
        self.label_62.setMinimumSize(QtCore.QSize(30, 20))
        self.label_62.setMaximumSize(QtCore.QSize(30, 20))
        self.label_62.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_62.setStyleSheet(_fromUtf8(""))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout.addWidget(self.label_62, 1, 2, 1, 1)
        self.b1ab = QtGui.QSpinBox(Page_isf)
        self.b1ab.setEnabled(True)
        self.b1ab.setMinimumSize(QtCore.QSize(60, 20))
        self.b1ab.setMaximumSize(QtCore.QSize(60, 20))
        self.b1ab.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1ab.setWrapping(False)
        self.b1ab.setFrame(True)
        self.b1ab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1ab.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1ab.setAccelerated(False)
        self.b1ab.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1ab.setKeyboardTracking(True)
        self.b1ab.setSuffix(_fromUtf8(""))
        self.b1ab.setPrefix(_fromUtf8(""))
        self.b1ab.setMinimum(0)
        self.b1ab.setMaximum(99999999)
        self.b1ab.setSingleStep(10000)
        self.b1ab.setProperty("value", 0)
        self.b1ab.setObjectName(_fromUtf8("b1ab"))
        self.gridLayout.addWidget(self.b1ab, 1, 3, 1, 1)
        self.label_66 = QtGui.QLabel(Page_isf)
        self.label_66.setStyleSheet(_fromUtf8(""))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout.addWidget(self.label_66, 2, 0, 1, 1)
        self.label_63 = QtGui.QLabel(Page_isf)
        self.label_63.setMinimumSize(QtCore.QSize(30, 20))
        self.label_63.setMaximumSize(QtCore.QSize(30, 20))
        self.label_63.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_63.setStyleSheet(_fromUtf8(""))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout.addWidget(self.label_63, 2, 2, 1, 1)
        self.b1ac = QtGui.QSpinBox(Page_isf)
        self.b1ac.setEnabled(True)
        self.b1ac.setMinimumSize(QtCore.QSize(60, 20))
        self.b1ac.setMaximumSize(QtCore.QSize(60, 20))
        self.b1ac.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1ac.setWrapping(False)
        self.b1ac.setFrame(True)
        self.b1ac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1ac.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1ac.setAccelerated(False)
        self.b1ac.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1ac.setKeyboardTracking(True)
        self.b1ac.setSuffix(_fromUtf8(""))
        self.b1ac.setPrefix(_fromUtf8(""))
        self.b1ac.setMinimum(0)
        self.b1ac.setMaximum(99999999)
        self.b1ac.setSingleStep(10000)
        self.b1ac.setProperty("value", 0)
        self.b1ac.setObjectName(_fromUtf8("b1ac"))
        self.gridLayout.addWidget(self.b1ac, 2, 3, 1, 1)
        self.label_61 = QtGui.QLabel(Page_isf)
        self.label_61.setEnabled(True)
        self.label_61.setStyleSheet(_fromUtf8(""))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout.addWidget(self.label_61, 3, 0, 1, 1)
        self.label_67 = QtGui.QLabel(Page_isf)
        self.label_67.setStyleSheet(_fromUtf8(""))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout.addWidget(self.label_67, 4, 0, 1, 1)
        self.label_64 = QtGui.QLabel(Page_isf)
        self.label_64.setMinimumSize(QtCore.QSize(30, 20))
        self.label_64.setMaximumSize(QtCore.QSize(30, 20))
        self.label_64.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_64.setStyleSheet(_fromUtf8(""))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout.addWidget(self.label_64, 4, 2, 1, 1)
        self.b1bc = QtGui.QSpinBox(Page_isf)
        self.b1bc.setEnabled(True)
        self.b1bc.setMinimumSize(QtCore.QSize(60, 20))
        self.b1bc.setMaximumSize(QtCore.QSize(60, 20))
        self.b1bc.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1bc.setWrapping(False)
        self.b1bc.setFrame(True)
        self.b1bc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1bc.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1bc.setAccelerated(False)
        self.b1bc.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1bc.setKeyboardTracking(True)
        self.b1bc.setSuffix(_fromUtf8(""))
        self.b1bc.setPrefix(_fromUtf8(""))
        self.b1bc.setMinimum(0)
        self.b1bc.setMaximum(99999999)
        self.b1bc.setSingleStep(10000)
        self.b1bc.setProperty("value", 0)
        self.b1bc.setObjectName(_fromUtf8("b1bc"))
        self.gridLayout.addWidget(self.b1bc, 4, 3, 1, 1)
        self.label_69 = QtGui.QLabel(Page_isf)
        self.label_69.setStyleSheet(_fromUtf8(""))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout.addWidget(self.label_69, 5, 0, 1, 1)
        self.label_68 = QtGui.QLabel(Page_isf)
        self.label_68.setMinimumSize(QtCore.QSize(30, 20))
        self.label_68.setMaximumSize(QtCore.QSize(30, 20))
        self.label_68.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_68.setStyleSheet(_fromUtf8(""))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout.addWidget(self.label_68, 5, 2, 1, 1)
        self.b1be = QtGui.QSpinBox(Page_isf)
        self.b1be.setEnabled(True)
        self.b1be.setMinimumSize(QtCore.QSize(60, 20))
        self.b1be.setMaximumSize(QtCore.QSize(60, 20))
        self.b1be.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1be.setWrapping(False)
        self.b1be.setFrame(True)
        self.b1be.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1be.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1be.setAccelerated(False)
        self.b1be.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1be.setKeyboardTracking(True)
        self.b1be.setSuffix(_fromUtf8(""))
        self.b1be.setPrefix(_fromUtf8(""))
        self.b1be.setMinimum(0)
        self.b1be.setMaximum(99999999)
        self.b1be.setSingleStep(10000)
        self.b1be.setProperty("value", 0)
        self.b1be.setObjectName(_fromUtf8("b1be"))
        self.gridLayout.addWidget(self.b1be, 5, 3, 1, 1)
        self.label_70 = QtGui.QLabel(Page_isf)
        self.label_70.setStyleSheet(_fromUtf8(""))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout.addWidget(self.label_70, 6, 0, 1, 1)
        self.label_72 = QtGui.QLabel(Page_isf)
        self.label_72.setMinimumSize(QtCore.QSize(30, 20))
        self.label_72.setMaximumSize(QtCore.QSize(30, 20))
        self.label_72.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_72.setStyleSheet(_fromUtf8(""))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 6, 2, 1, 1)
        self.b1bh = QtGui.QSpinBox(Page_isf)
        self.b1bh.setEnabled(True)
        self.b1bh.setMinimumSize(QtCore.QSize(60, 20))
        self.b1bh.setMaximumSize(QtCore.QSize(60, 20))
        self.b1bh.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1bh.setWrapping(False)
        self.b1bh.setFrame(True)
        self.b1bh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1bh.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1bh.setAccelerated(False)
        self.b1bh.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1bh.setKeyboardTracking(True)
        self.b1bh.setSuffix(_fromUtf8(""))
        self.b1bh.setPrefix(_fromUtf8(""))
        self.b1bh.setMinimum(0)
        self.b1bh.setMaximum(99999999)
        self.b1bh.setSingleStep(10000)
        self.b1bh.setProperty("value", 0)
        self.b1bh.setObjectName(_fromUtf8("b1bh"))
        self.gridLayout.addWidget(self.b1bh, 6, 3, 1, 1)
        self.label_71 = QtGui.QLabel(Page_isf)
        self.label_71.setStyleSheet(_fromUtf8(""))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout.addWidget(self.label_71, 7, 0, 1, 1)
        self.label_73 = QtGui.QLabel(Page_isf)
        self.label_73.setMinimumSize(QtCore.QSize(30, 20))
        self.label_73.setMaximumSize(QtCore.QSize(30, 20))
        self.label_73.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_73.setStyleSheet(_fromUtf8(""))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout.addWidget(self.label_73, 7, 2, 1, 1)
        self.b1bk = QtGui.QSpinBox(Page_isf)
        self.b1bk.setEnabled(True)
        self.b1bk.setMinimumSize(QtCore.QSize(60, 20))
        self.b1bk.setMaximumSize(QtCore.QSize(60, 20))
        self.b1bk.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1bk.setWrapping(False)
        self.b1bk.setFrame(True)
        self.b1bk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1bk.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1bk.setAccelerated(False)
        self.b1bk.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1bk.setKeyboardTracking(True)
        self.b1bk.setSuffix(_fromUtf8(""))
        self.b1bk.setPrefix(_fromUtf8(""))
        self.b1bk.setMinimum(0)
        self.b1bk.setMaximum(99999999)
        self.b1bk.setSingleStep(10000)
        self.b1bk.setProperty("value", 0)
        self.b1bk.setObjectName(_fromUtf8("b1bk"))
        self.gridLayout.addWidget(self.b1bk, 7, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_123 = QtGui.QLabel(Page_isf)
        self.label_123.setStyleSheet(_fromUtf8(""))
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout_4.addWidget(self.label_123, 0, 0, 1, 1)
        self.label_110 = QtGui.QLabel(Page_isf)
        self.label_110.setStyleSheet(_fromUtf8(""))
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout_4.addWidget(self.label_110, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_121 = QtGui.QLabel(Page_isf)
        self.label_121.setMinimumSize(QtCore.QSize(30, 20))
        self.label_121.setMaximumSize(QtCore.QSize(30, 20))
        self.label_121.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_121.setStyleSheet(_fromUtf8(""))
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout_4.addWidget(self.label_121, 1, 2, 1, 1)
        self.b1cl = QtGui.QSpinBox(Page_isf)
        self.b1cl.setEnabled(True)
        self.b1cl.setMinimumSize(QtCore.QSize(60, 20))
        self.b1cl.setMaximumSize(QtCore.QSize(60, 20))
        self.b1cl.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1cl.setWrapping(False)
        self.b1cl.setFrame(True)
        self.b1cl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1cl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1cl.setAccelerated(False)
        self.b1cl.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1cl.setKeyboardTracking(True)
        self.b1cl.setSuffix(_fromUtf8(""))
        self.b1cl.setPrefix(_fromUtf8(""))
        self.b1cl.setMinimum(0)
        self.b1cl.setMaximum(99999999)
        self.b1cl.setSingleStep(10000)
        self.b1cl.setProperty("value", 0)
        self.b1cl.setObjectName(_fromUtf8("b1cl"))
        self.gridLayout_4.addWidget(self.b1cl, 1, 3, 1, 1)
        self.label_109 = QtGui.QLabel(Page_isf)
        self.label_109.setStyleSheet(_fromUtf8(""))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout_4.addWidget(self.label_109, 2, 0, 1, 1)
        self.label_114 = QtGui.QLabel(Page_isf)
        self.label_114.setMinimumSize(QtCore.QSize(30, 20))
        self.label_114.setMaximumSize(QtCore.QSize(30, 20))
        self.label_114.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_114.setStyleSheet(_fromUtf8(""))
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.gridLayout_4.addWidget(self.label_114, 2, 2, 1, 1)
        self.b1cb = QtGui.QSpinBox(Page_isf)
        self.b1cb.setEnabled(True)
        self.b1cb.setMinimumSize(QtCore.QSize(60, 20))
        self.b1cb.setMaximumSize(QtCore.QSize(60, 20))
        self.b1cb.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1cb.setWrapping(False)
        self.b1cb.setFrame(True)
        self.b1cb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1cb.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1cb.setAccelerated(False)
        self.b1cb.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1cb.setKeyboardTracking(True)
        self.b1cb.setSuffix(_fromUtf8(""))
        self.b1cb.setPrefix(_fromUtf8(""))
        self.b1cb.setMinimum(0)
        self.b1cb.setMaximum(99999999)
        self.b1cb.setSingleStep(10000)
        self.b1cb.setProperty("value", 0)
        self.b1cb.setObjectName(_fromUtf8("b1cb"))
        self.gridLayout_4.addWidget(self.b1cb, 2, 3, 1, 1)
        self.label_111 = QtGui.QLabel(Page_isf)
        self.label_111.setStyleSheet(_fromUtf8(""))
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_4.addWidget(self.label_111, 3, 0, 1, 1)
        self.label_115 = QtGui.QLabel(Page_isf)
        self.label_115.setMinimumSize(QtCore.QSize(30, 20))
        self.label_115.setMaximumSize(QtCore.QSize(30, 20))
        self.label_115.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_115.setStyleSheet(_fromUtf8(""))
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.gridLayout_4.addWidget(self.label_115, 3, 2, 1, 1)
        self.b1cd = QtGui.QSpinBox(Page_isf)
        self.b1cd.setEnabled(True)
        self.b1cd.setMinimumSize(QtCore.QSize(60, 20))
        self.b1cd.setMaximumSize(QtCore.QSize(60, 20))
        self.b1cd.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1cd.setWrapping(False)
        self.b1cd.setFrame(True)
        self.b1cd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1cd.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1cd.setAccelerated(False)
        self.b1cd.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1cd.setKeyboardTracking(True)
        self.b1cd.setSuffix(_fromUtf8(""))
        self.b1cd.setPrefix(_fromUtf8(""))
        self.b1cd.setMinimum(0)
        self.b1cd.setMaximum(99999999)
        self.b1cd.setSingleStep(10000)
        self.b1cd.setProperty("value", 0)
        self.b1cd.setObjectName(_fromUtf8("b1cd"))
        self.gridLayout_4.addWidget(self.b1cd, 3, 3, 1, 1)
        self.label_112 = QtGui.QLabel(Page_isf)
        self.label_112.setStyleSheet(_fromUtf8(""))
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout_4.addWidget(self.label_112, 4, 0, 1, 1)
        self.label_116 = QtGui.QLabel(Page_isf)
        self.label_116.setMinimumSize(QtCore.QSize(30, 20))
        self.label_116.setMaximumSize(QtCore.QSize(30, 20))
        self.label_116.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_116.setStyleSheet(_fromUtf8(""))
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.gridLayout_4.addWidget(self.label_116, 4, 2, 1, 1)
        self.b1ce = QtGui.QSpinBox(Page_isf)
        self.b1ce.setEnabled(True)
        self.b1ce.setMinimumSize(QtCore.QSize(60, 20))
        self.b1ce.setMaximumSize(QtCore.QSize(60, 20))
        self.b1ce.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1ce.setWrapping(False)
        self.b1ce.setFrame(True)
        self.b1ce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1ce.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1ce.setAccelerated(False)
        self.b1ce.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1ce.setKeyboardTracking(True)
        self.b1ce.setSuffix(_fromUtf8(""))
        self.b1ce.setPrefix(_fromUtf8(""))
        self.b1ce.setMinimum(0)
        self.b1ce.setMaximum(99999999)
        self.b1ce.setSingleStep(10000)
        self.b1ce.setProperty("value", 0)
        self.b1ce.setObjectName(_fromUtf8("b1ce"))
        self.gridLayout_4.addWidget(self.b1ce, 4, 3, 1, 1)
        self.label_113 = QtGui.QLabel(Page_isf)
        self.label_113.setStyleSheet(_fromUtf8(""))
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.gridLayout_4.addWidget(self.label_113, 5, 0, 1, 1)
        self.label_117 = QtGui.QLabel(Page_isf)
        self.label_117.setMinimumSize(QtCore.QSize(30, 20))
        self.label_117.setMaximumSize(QtCore.QSize(30, 20))
        self.label_117.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_117.setStyleSheet(_fromUtf8(""))
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout_4.addWidget(self.label_117, 5, 2, 1, 1)
        self.b1cf = QtGui.QSpinBox(Page_isf)
        self.b1cf.setEnabled(True)
        self.b1cf.setMinimumSize(QtCore.QSize(60, 20))
        self.b1cf.setMaximumSize(QtCore.QSize(60, 20))
        self.b1cf.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1cf.setWrapping(False)
        self.b1cf.setFrame(True)
        self.b1cf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1cf.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1cf.setAccelerated(False)
        self.b1cf.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1cf.setKeyboardTracking(True)
        self.b1cf.setSuffix(_fromUtf8(""))
        self.b1cf.setPrefix(_fromUtf8(""))
        self.b1cf.setMinimum(0)
        self.b1cf.setMaximum(99999999)
        self.b1cf.setSingleStep(10000)
        self.b1cf.setProperty("value", 0)
        self.b1cf.setObjectName(_fromUtf8("b1cf"))
        self.gridLayout_4.addWidget(self.b1cf, 5, 3, 1, 1)
        self.label_118 = QtGui.QLabel(Page_isf)
        self.label_118.setStyleSheet(_fromUtf8(""))
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.gridLayout_4.addWidget(self.label_118, 6, 0, 1, 1)
        self.label_119 = QtGui.QLabel(Page_isf)
        self.label_119.setMinimumSize(QtCore.QSize(30, 20))
        self.label_119.setMaximumSize(QtCore.QSize(30, 20))
        self.label_119.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_119.setStyleSheet(_fromUtf8(""))
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.gridLayout_4.addWidget(self.label_119, 6, 2, 1, 1)
        self.b1cg = QtGui.QSpinBox(Page_isf)
        self.b1cg.setEnabled(True)
        self.b1cg.setMinimumSize(QtCore.QSize(60, 20))
        self.b1cg.setMaximumSize(QtCore.QSize(60, 20))
        self.b1cg.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b1cg.setWrapping(False)
        self.b1cg.setFrame(True)
        self.b1cg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b1cg.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b1cg.setAccelerated(False)
        self.b1cg.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b1cg.setKeyboardTracking(True)
        self.b1cg.setSuffix(_fromUtf8(""))
        self.b1cg.setPrefix(_fromUtf8(""))
        self.b1cg.setMinimum(0)
        self.b1cg.setMaximum(99999999)
        self.b1cg.setSingleStep(10000)
        self.b1cg.setProperty("value", 0)
        self.b1cg.setObjectName(_fromUtf8("b1cg"))
        self.gridLayout_4.addWidget(self.b1cg, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(Page_isf)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_107 = QtGui.QLabel(Page_isf)
        self.label_107.setStyleSheet(_fromUtf8(""))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_5.addWidget(self.label_107, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.label_108 = QtGui.QLabel(Page_isf)
        self.label_108.setMinimumSize(QtCore.QSize(30, 20))
        self.label_108.setMaximumSize(QtCore.QSize(30, 20))
        self.label_108.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_108.setStyleSheet(_fromUtf8(""))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_5.addWidget(self.label_108, 1, 2, 1, 1)
        self.b2gh = QtGui.QSpinBox(Page_isf)
        self.b2gh.setEnabled(True)
        self.b2gh.setMinimumSize(QtCore.QSize(60, 20))
        self.b2gh.setMaximumSize(QtCore.QSize(60, 20))
        self.b2gh.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2gh.setWrapping(False)
        self.b2gh.setFrame(True)
        self.b2gh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2gh.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2gh.setAccelerated(False)
        self.b2gh.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2gh.setKeyboardTracking(True)
        self.b2gh.setSuffix(_fromUtf8(""))
        self.b2gh.setPrefix(_fromUtf8(""))
        self.b2gh.setMinimum(0)
        self.b2gh.setMaximum(99999999)
        self.b2gh.setSingleStep(10000)
        self.b2gh.setProperty("value", 0)
        self.b2gh.setObjectName(_fromUtf8("b2gh"))
        self.gridLayout_5.addWidget(self.b2gh, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_74 = QtGui.QLabel(Page_isf)
        self.label_74.setStyleSheet(_fromUtf8(""))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_2.addWidget(self.label_74, 0, 0, 1, 1)
        self.label_78 = QtGui.QLabel(Page_isf)
        self.label_78.setStyleSheet(_fromUtf8(""))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_2.addWidget(self.label_78, 1, 0, 1, 1)
        self.label_75 = QtGui.QLabel(Page_isf)
        self.label_75.setStyleSheet(_fromUtf8(""))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_2.addWidget(self.label_75, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        self.label_77 = QtGui.QLabel(Page_isf)
        self.label_77.setMinimumSize(QtCore.QSize(30, 20))
        self.label_77.setMaximumSize(QtCore.QSize(30, 20))
        self.label_77.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_77.setStyleSheet(_fromUtf8(""))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_2.addWidget(self.label_77, 2, 2, 1, 1)
        self.b2mt = QtGui.QSpinBox(Page_isf)
        self.b2mt.setEnabled(True)
        self.b2mt.setMinimumSize(QtCore.QSize(60, 20))
        self.b2mt.setMaximumSize(QtCore.QSize(60, 20))
        self.b2mt.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2mt.setWrapping(False)
        self.b2mt.setFrame(True)
        self.b2mt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2mt.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2mt.setAccelerated(False)
        self.b2mt.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2mt.setKeyboardTracking(True)
        self.b2mt.setSuffix(_fromUtf8(""))
        self.b2mt.setPrefix(_fromUtf8(""))
        self.b2mt.setMinimum(0)
        self.b2mt.setMaximum(99999999)
        self.b2mt.setSingleStep(10000)
        self.b2mt.setProperty("value", 0)
        self.b2mt.setObjectName(_fromUtf8("b2mt"))
        self.gridLayout_2.addWidget(self.b2mt, 2, 3, 1, 1)
        self.label_80 = QtGui.QLabel(Page_isf)
        self.label_80.setMinimumSize(QtCore.QSize(30, 20))
        self.label_80.setMaximumSize(QtCore.QSize(30, 20))
        self.label_80.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_80.setStyleSheet(_fromUtf8(""))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_2.addWidget(self.label_80, 2, 4, 1, 1)
        self.b2ne = QtGui.QSpinBox(Page_isf)
        self.b2ne.setEnabled(True)
        self.b2ne.setMinimumSize(QtCore.QSize(60, 20))
        self.b2ne.setMaximumSize(QtCore.QSize(60, 20))
        self.b2ne.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2ne.setWrapping(False)
        self.b2ne.setFrame(True)
        self.b2ne.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2ne.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2ne.setAccelerated(False)
        self.b2ne.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2ne.setKeyboardTracking(True)
        self.b2ne.setSuffix(_fromUtf8(""))
        self.b2ne.setPrefix(_fromUtf8(""))
        self.b2ne.setMinimum(0)
        self.b2ne.setMaximum(99999999)
        self.b2ne.setSingleStep(10000)
        self.b2ne.setProperty("value", 0)
        self.b2ne.setObjectName(_fromUtf8("b2ne"))
        self.gridLayout_2.addWidget(self.b2ne, 2, 5, 1, 1)
        self.label_76 = QtGui.QLabel(Page_isf)
        self.label_76.setStyleSheet(_fromUtf8(""))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_2.addWidget(self.label_76, 3, 0, 1, 1)
        self.label_84 = QtGui.QLabel(Page_isf)
        self.label_84.setMinimumSize(QtCore.QSize(30, 20))
        self.label_84.setMaximumSize(QtCore.QSize(30, 20))
        self.label_84.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_84.setStyleSheet(_fromUtf8(""))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_2.addWidget(self.label_84, 3, 2, 1, 1)
        self.b2mv = QtGui.QSpinBox(Page_isf)
        self.b2mv.setEnabled(True)
        self.b2mv.setMinimumSize(QtCore.QSize(60, 20))
        self.b2mv.setMaximumSize(QtCore.QSize(60, 20))
        self.b2mv.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2mv.setWrapping(False)
        self.b2mv.setFrame(True)
        self.b2mv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2mv.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2mv.setAccelerated(False)
        self.b2mv.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2mv.setKeyboardTracking(True)
        self.b2mv.setSuffix(_fromUtf8(""))
        self.b2mv.setPrefix(_fromUtf8(""))
        self.b2mv.setMinimum(0)
        self.b2mv.setMaximum(99999999)
        self.b2mv.setSingleStep(10000)
        self.b2mv.setProperty("value", 0)
        self.b2mv.setObjectName(_fromUtf8("b2mv"))
        self.gridLayout_2.addWidget(self.b2mv, 3, 3, 1, 1)
        self.label_89 = QtGui.QLabel(Page_isf)
        self.label_89.setMinimumSize(QtCore.QSize(30, 20))
        self.label_89.setMaximumSize(QtCore.QSize(30, 20))
        self.label_89.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_89.setStyleSheet(_fromUtf8(""))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_2.addWidget(self.label_89, 3, 4, 1, 1)
        self.b2nf = QtGui.QSpinBox(Page_isf)
        self.b2nf.setEnabled(True)
        self.b2nf.setMinimumSize(QtCore.QSize(60, 20))
        self.b2nf.setMaximumSize(QtCore.QSize(60, 20))
        self.b2nf.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2nf.setWrapping(False)
        self.b2nf.setFrame(True)
        self.b2nf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2nf.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2nf.setAccelerated(False)
        self.b2nf.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2nf.setKeyboardTracking(True)
        self.b2nf.setSuffix(_fromUtf8(""))
        self.b2nf.setPrefix(_fromUtf8(""))
        self.b2nf.setMinimum(0)
        self.b2nf.setMaximum(99999999)
        self.b2nf.setSingleStep(10000)
        self.b2nf.setProperty("value", 0)
        self.b2nf.setObjectName(_fromUtf8("b2nf"))
        self.gridLayout_2.addWidget(self.b2nf, 3, 5, 1, 1)
        self.label_81 = QtGui.QLabel(Page_isf)
        self.label_81.setStyleSheet(_fromUtf8(""))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_2.addWidget(self.label_81, 4, 0, 1, 1)
        self.label_85 = QtGui.QLabel(Page_isf)
        self.label_85.setMinimumSize(QtCore.QSize(30, 20))
        self.label_85.setMaximumSize(QtCore.QSize(30, 20))
        self.label_85.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_85.setStyleSheet(_fromUtf8(""))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_2.addWidget(self.label_85, 4, 2, 1, 1)
        self.b2mx = QtGui.QSpinBox(Page_isf)
        self.b2mx.setEnabled(True)
        self.b2mx.setMinimumSize(QtCore.QSize(60, 20))
        self.b2mx.setMaximumSize(QtCore.QSize(60, 20))
        self.b2mx.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2mx.setWrapping(False)
        self.b2mx.setFrame(True)
        self.b2mx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2mx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2mx.setAccelerated(False)
        self.b2mx.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2mx.setKeyboardTracking(True)
        self.b2mx.setSuffix(_fromUtf8(""))
        self.b2mx.setPrefix(_fromUtf8(""))
        self.b2mx.setMinimum(0)
        self.b2mx.setMaximum(99999999)
        self.b2mx.setSingleStep(10000)
        self.b2mx.setProperty("value", 0)
        self.b2mx.setObjectName(_fromUtf8("b2mx"))
        self.gridLayout_2.addWidget(self.b2mx, 4, 3, 1, 1)
        self.label_82 = QtGui.QLabel(Page_isf)
        self.label_82.setStyleSheet(_fromUtf8(""))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_2.addWidget(self.label_82, 5, 0, 1, 1)
        self.label_86 = QtGui.QLabel(Page_isf)
        self.label_86.setMinimumSize(QtCore.QSize(30, 20))
        self.label_86.setMaximumSize(QtCore.QSize(30, 20))
        self.label_86.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_86.setStyleSheet(_fromUtf8(""))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_2.addWidget(self.label_86, 5, 2, 1, 1)
        self.b2na = QtGui.QSpinBox(Page_isf)
        self.b2na.setEnabled(True)
        self.b2na.setMinimumSize(QtCore.QSize(60, 20))
        self.b2na.setMaximumSize(QtCore.QSize(60, 20))
        self.b2na.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2na.setWrapping(False)
        self.b2na.setFrame(True)
        self.b2na.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2na.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2na.setAccelerated(False)
        self.b2na.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2na.setKeyboardTracking(True)
        self.b2na.setSuffix(_fromUtf8(""))
        self.b2na.setPrefix(_fromUtf8(""))
        self.b2na.setMinimum(0)
        self.b2na.setMaximum(99999999)
        self.b2na.setSingleStep(10000)
        self.b2na.setProperty("value", 0)
        self.b2na.setObjectName(_fromUtf8("b2na"))
        self.gridLayout_2.addWidget(self.b2na, 5, 3, 1, 1)
        self.label_83 = QtGui.QLabel(Page_isf)
        self.label_83.setStyleSheet(_fromUtf8(""))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_2.addWidget(self.label_83, 6, 0, 1, 1)
        self.label_87 = QtGui.QLabel(Page_isf)
        self.label_87.setMinimumSize(QtCore.QSize(30, 20))
        self.label_87.setMaximumSize(QtCore.QSize(30, 20))
        self.label_87.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_87.setStyleSheet(_fromUtf8(""))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_2.addWidget(self.label_87, 6, 2, 1, 1)
        self.b2nc = QtGui.QSpinBox(Page_isf)
        self.b2nc.setEnabled(True)
        self.b2nc.setMinimumSize(QtCore.QSize(60, 20))
        self.b2nc.setMaximumSize(QtCore.QSize(60, 20))
        self.b2nc.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b2nc.setWrapping(False)
        self.b2nc.setFrame(True)
        self.b2nc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b2nc.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b2nc.setAccelerated(False)
        self.b2nc.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b2nc.setKeyboardTracking(True)
        self.b2nc.setSuffix(_fromUtf8(""))
        self.b2nc.setPrefix(_fromUtf8(""))
        self.b2nc.setMinimum(0)
        self.b2nc.setMaximum(99999999)
        self.b2nc.setSingleStep(10000)
        self.b2nc.setProperty("value", 0)
        self.b2nc.setObjectName(_fromUtf8("b2nc"))
        self.gridLayout_2.addWidget(self.b2nc, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_4 = QtGui.QLabel(Page_isf)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 4)
        self.label_105 = QtGui.QLabel(Page_isf)
        self.label_105.setStyleSheet(_fromUtf8(""))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_6.addWidget(self.label_105, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.label_106 = QtGui.QLabel(Page_isf)
        self.label_106.setMinimumSize(QtCore.QSize(30, 20))
        self.label_106.setMaximumSize(QtCore.QSize(30, 20))
        self.label_106.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_106.setStyleSheet(_fromUtf8(""))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_6.addWidget(self.label_106, 1, 2, 1, 1)
        self.b4rs = QtGui.QSpinBox(Page_isf)
        self.b4rs.setEnabled(True)
        self.b4rs.setMinimumSize(QtCore.QSize(60, 20))
        self.b4rs.setMaximumSize(QtCore.QSize(60, 20))
        self.b4rs.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.b4rs.setWrapping(False)
        self.b4rs.setFrame(True)
        self.b4rs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.b4rs.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.b4rs.setAccelerated(False)
        self.b4rs.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.b4rs.setKeyboardTracking(True)
        self.b4rs.setSuffix(_fromUtf8(""))
        self.b4rs.setPrefix(_fromUtf8(""))
        self.b4rs.setMinimum(0)
        self.b4rs.setMaximum(99999999)
        self.b4rs.setSingleStep(10000)
        self.b4rs.setProperty("value", 0)
        self.b4rs.setObjectName(_fromUtf8("b4rs"))
        self.gridLayout_6.addWidget(self.b4rs, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        spacerItem5 = QtGui.QSpacerItem(20, 53, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(Page_isf)
        QtCore.QMetaObject.connectSlotsByName(Page_isf)

    def retranslateUi(self, Page_isf):
        Page_isf.setWindowTitle(QtGui.QApplication.translate("Page_isf", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Page_isf", "1| ACTIF BRUT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("Page_isf", "IMMEUBLES BÂTIS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("Page_isf", "Résidence principale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("Page_isf", "1AB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("Page_isf", "Autres immeubles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("Page_isf", "1AC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("Page_isf", "IMMEUBLES NON BÂTIS, PARTS DE GROUPEMENTS FORESTIERS OU FONCIERS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("Page_isf", "Bois, forêts et groupements forestiers ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("Page_isf", "1BC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("Page_isf", "Biens ruraux loués à long terme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("Page_isf", "1BE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("Page_isf", "Parts de Groupements Fonciers Agricoles et de Groupements Agricoles Fonciers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("Page_isf", "1BH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("Page_isf", "Autres biens", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("Page_isf", "1BK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_123.setText(QtGui.QApplication.translate("Page_isf", "DROITS SOCIAUX-VALEURS MOBILIERES", None, QtGui.QApplication.UnicodeUTF8))
        self.label_123.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_110.setText(QtGui.QApplication.translate("Page_isf", "Parts ou actions détenues par les salariés et mandataires sociaux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_110.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_121.setText(QtGui.QApplication.translate("Page_isf", "1CL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_121.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_109.setText(QtGui.QApplication.translate("Page_isf", "Parts ou actions avec engagement de conservations de 6 ans minimum ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_109.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_114.setText(QtGui.QApplication.translate("Page_isf", "1CB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_114.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_111.setText(QtGui.QApplication.translate("Page_isf", "Droits sociaux de sociétés dans lesquelles vous exercez une fonction ou une activité", None, QtGui.QApplication.UnicodeUTF8))
        self.label_111.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_115.setText(QtGui.QApplication.translate("Page_isf", "1CD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_115.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_112.setText(QtGui.QApplication.translate("Page_isf", "Autres valeurs mobilières", None, QtGui.QApplication.UnicodeUTF8))
        self.label_112.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_116.setText(QtGui.QApplication.translate("Page_isf", "1CE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_116.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_113.setText(QtGui.QApplication.translate("Page_isf", "Liquidités ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_113.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_117.setText(QtGui.QApplication.translate("Page_isf", "1CF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_117.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_118.setText(QtGui.QApplication.translate("Page_isf", "Autres biens meubles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_118.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_119.setText(QtGui.QApplication.translate("Page_isf", "1CG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_119.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Page_isf", "2| PASSIF, AUTRES DEDUCTIONS ET REDUCTIONS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_107.setText(QtGui.QApplication.translate("Page_isf", "Total du passif et autres déductions ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_107.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_108.setText(QtGui.QApplication.translate("Page_isf", "2GH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_108.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("Page_isf", "REDUCTIONS ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("Page_isf", "Pour investissements dans les PME", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("Page_isf", "Directs dans une société ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("Page_isf", "2MT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("Page_isf", "2NE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("Page_isf", "Par sociétés interposées ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setText(QtGui.QApplication.translate("Page_isf", "2MV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("Page_isf", "2NF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("Page_isf", "Par le biais de FIP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("Page_isf", "2MX", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("Page_isf", "Par le biais de FCPI ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("Page_isf", "2NA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_83.setText(QtGui.QApplication.translate("Page_isf", "Pour dons à certains organismes d\'intérêt général", None, QtGui.QApplication.UnicodeUTF8))
        self.label_83.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("Page_isf", "2NC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Page_isf", "4| IMPUTATION DE L\'IMPOT SUR LA FORTUNE ACQUITTE HORS DE FRANCE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setProperty("class", QtGui.QApplication.translate("Page_isf", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_105.setText(QtGui.QApplication.translate("Page_isf", "Total du montant acquitté hors de France", None, QtGui.QApplication.UnicodeUTF8))
        self.label_105.setProperty("class", QtGui.QApplication.translate("Page_isf", "texte01", None, QtGui.QApplication.UnicodeUTF8))
        self.label_106.setText(QtGui.QApplication.translate("Page_isf", "4RS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_106.setProperty("class", QtGui.QApplication.translate("Page_isf", "code", None, QtGui.QApplication.UnicodeUTF8))

