# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page06.ui'
#
# Created: Sun Nov 04 23:45:52 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Page06(object):
    def setupUi(self, Page06):
        Page06.setObjectName(_fromUtf8("Page06"))
        Page06.resize(730, 577)
        Page06.setMinimumSize(QtCore.QSize(730, 0))
        Page06.setMaximumSize(QtCore.QSize(730, 16777215))
        Page06.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(Page06)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(Page06)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_58 = QtGui.QLabel(Page06)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout.addWidget(self.label_58)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_12 = QtGui.QLabel(Page06)
        self.label_12.setMinimumSize(QtCore.QSize(25, 20))
        self.label_12.setMaximumSize(QtCore.QSize(25, 20))
        self.label_12.setStyleSheet(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.f6de = QtGui.QSpinBox(Page06)
        self.f6de.setEnabled(True)
        self.f6de.setMinimumSize(QtCore.QSize(60, 20))
        self.f6de.setMaximumSize(QtCore.QSize(60, 20))
        self.f6de.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6de.setWrapping(False)
        self.f6de.setFrame(True)
        self.f6de.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6de.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6de.setAccelerated(False)
        self.f6de.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6de.setKeyboardTracking(True)
        self.f6de.setSuffix(_fromUtf8(""))
        self.f6de.setPrefix(_fromUtf8(""))
        self.f6de.setMinimum(0)
        self.f6de.setMaximum(999999)
        self.f6de.setSingleStep(1000)
        self.f6de.setProperty("value", 0)
        self.f6de.setObjectName(_fromUtf8("f6de"))
        self.horizontalLayout.addWidget(self.f6de)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_59 = QtGui.QLabel(Page06)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_2.addWidget(self.label_59, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Page06)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.label = QtGui.QLabel(Page06)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(Page06)
        self.label_14.setMinimumSize(QtCore.QSize(25, 20))
        self.label_14.setMaximumSize(QtCore.QSize(25, 20))
        self.label_14.setStyleSheet(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 3, 1, 1)
        self.f6gi = QtGui.QSpinBox(Page06)
        self.f6gi.setEnabled(True)
        self.f6gi.setMinimumSize(QtCore.QSize(60, 20))
        self.f6gi.setMaximumSize(QtCore.QSize(60, 20))
        self.f6gi.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6gi.setWrapping(False)
        self.f6gi.setFrame(True)
        self.f6gi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6gi.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6gi.setAccelerated(False)
        self.f6gi.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6gi.setKeyboardTracking(True)
        self.f6gi.setSuffix(_fromUtf8(""))
        self.f6gi.setPrefix(_fromUtf8(""))
        self.f6gi.setMinimum(0)
        self.f6gi.setMaximum(999999)
        self.f6gi.setSingleStep(1000)
        self.f6gi.setProperty("value", 0)
        self.f6gi.setObjectName(_fromUtf8("f6gi"))
        self.gridLayout_2.addWidget(self.f6gi, 1, 4, 1, 1)
        self.label_42 = QtGui.QLabel(Page06)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 1, 5, 1, 1)
        self.label_13 = QtGui.QLabel(Page06)
        self.label_13.setMinimumSize(QtCore.QSize(25, 20))
        self.label_13.setMaximumSize(QtCore.QSize(25, 20))
        self.label_13.setStyleSheet(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 6, 1, 1)
        self.f6gj = QtGui.QSpinBox(Page06)
        self.f6gj.setEnabled(True)
        self.f6gj.setMinimumSize(QtCore.QSize(60, 20))
        self.f6gj.setMaximumSize(QtCore.QSize(60, 20))
        self.f6gj.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6gj.setWrapping(False)
        self.f6gj.setFrame(True)
        self.f6gj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6gj.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6gj.setAccelerated(False)
        self.f6gj.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6gj.setKeyboardTracking(True)
        self.f6gj.setSuffix(_fromUtf8(""))
        self.f6gj.setPrefix(_fromUtf8(""))
        self.f6gj.setMinimum(0)
        self.f6gj.setMaximum(999999)
        self.f6gj.setSingleStep(1000)
        self.f6gj.setProperty("value", 0)
        self.f6gj.setObjectName(_fromUtf8("f6gj"))
        self.gridLayout_2.addWidget(self.f6gj, 1, 7, 1, 1)
        self.label_5 = QtGui.QLabel(Page06)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(Page06)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(Page06)
        self.label_16.setMinimumSize(QtCore.QSize(25, 20))
        self.label_16.setMaximumSize(QtCore.QSize(25, 20))
        self.label_16.setStyleSheet(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 3, 1, 1)
        self.f6el = QtGui.QSpinBox(Page06)
        self.f6el.setEnabled(True)
        self.f6el.setMinimumSize(QtCore.QSize(60, 20))
        self.f6el.setMaximumSize(QtCore.QSize(60, 20))
        self.f6el.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6el.setWrapping(False)
        self.f6el.setFrame(True)
        self.f6el.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6el.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6el.setAccelerated(False)
        self.f6el.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6el.setKeyboardTracking(True)
        self.f6el.setSuffix(_fromUtf8(""))
        self.f6el.setPrefix(_fromUtf8(""))
        self.f6el.setMinimum(0)
        self.f6el.setMaximum(999999)
        self.f6el.setSingleStep(1000)
        self.f6el.setProperty("value", 0)
        self.f6el.setObjectName(_fromUtf8("f6el"))
        self.gridLayout_2.addWidget(self.f6el, 2, 4, 1, 1)
        self.label_43 = QtGui.QLabel(Page06)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_2.addWidget(self.label_43, 2, 5, 1, 1)
        self.label_15 = QtGui.QLabel(Page06)
        self.label_15.setMinimumSize(QtCore.QSize(25, 20))
        self.label_15.setMaximumSize(QtCore.QSize(25, 20))
        self.label_15.setStyleSheet(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 6, 1, 1)
        self.f6em = QtGui.QSpinBox(Page06)
        self.f6em.setEnabled(True)
        self.f6em.setMinimumSize(QtCore.QSize(60, 20))
        self.f6em.setMaximumSize(QtCore.QSize(60, 20))
        self.f6em.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6em.setWrapping(False)
        self.f6em.setFrame(True)
        self.f6em.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6em.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6em.setAccelerated(False)
        self.f6em.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6em.setKeyboardTracking(True)
        self.f6em.setSuffix(_fromUtf8(""))
        self.f6em.setPrefix(_fromUtf8(""))
        self.f6em.setMinimum(0)
        self.f6em.setMaximum(999999)
        self.f6em.setSingleStep(1000)
        self.f6em.setProperty("value", 0)
        self.f6em.setObjectName(_fromUtf8("f6em"))
        self.gridLayout_2.addWidget(self.f6em, 2, 7, 1, 1)
        self.label_6 = QtGui.QLabel(Page06)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(Page06)
        self.label_17.setMinimumSize(QtCore.QSize(25, 20))
        self.label_17.setMaximumSize(QtCore.QSize(25, 20))
        self.label_17.setStyleSheet(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 6, 1, 1)
        self.f6gp = QtGui.QSpinBox(Page06)
        self.f6gp.setEnabled(True)
        self.f6gp.setMinimumSize(QtCore.QSize(60, 20))
        self.f6gp.setMaximumSize(QtCore.QSize(60, 20))
        self.f6gp.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6gp.setWrapping(False)
        self.f6gp.setFrame(True)
        self.f6gp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6gp.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6gp.setAccelerated(False)
        self.f6gp.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6gp.setKeyboardTracking(True)
        self.f6gp.setSuffix(_fromUtf8(""))
        self.f6gp.setPrefix(_fromUtf8(""))
        self.f6gp.setMinimum(0)
        self.f6gp.setMaximum(999999)
        self.f6gp.setSingleStep(1000)
        self.f6gp.setProperty("value", 0)
        self.f6gp.setObjectName(_fromUtf8("f6gp"))
        self.gridLayout_2.addWidget(self.f6gp, 3, 7, 1, 1)
        self.label_7 = QtGui.QLabel(Page06)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 1, 1, 2)
        self.label_18 = QtGui.QLabel(Page06)
        self.label_18.setMinimumSize(QtCore.QSize(25, 20))
        self.label_18.setMaximumSize(QtCore.QSize(25, 20))
        self.label_18.setStyleSheet(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 4, 6, 1, 1)
        self.f6gu = QtGui.QSpinBox(Page06)
        self.f6gu.setEnabled(True)
        self.f6gu.setMinimumSize(QtCore.QSize(60, 20))
        self.f6gu.setMaximumSize(QtCore.QSize(60, 20))
        self.f6gu.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6gu.setWrapping(False)
        self.f6gu.setFrame(True)
        self.f6gu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6gu.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6gu.setAccelerated(False)
        self.f6gu.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6gu.setKeyboardTracking(True)
        self.f6gu.setSuffix(_fromUtf8(""))
        self.f6gu.setPrefix(_fromUtf8(""))
        self.f6gu.setMinimum(0)
        self.f6gu.setMaximum(999999)
        self.f6gu.setSingleStep(1000)
        self.f6gu.setProperty("value", 0)
        self.f6gu.setObjectName(_fromUtf8("f6gu"))
        self.gridLayout_2.addWidget(self.f6gu, 4, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_61 = QtGui.QLabel(Page06)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout.addWidget(self.label_61, 0, 0, 1, 2)
        self.label_20 = QtGui.QLabel(Page06)
        self.label_20.setMinimumSize(QtCore.QSize(25, 20))
        self.label_20.setMaximumSize(QtCore.QSize(25, 20))
        self.label_20.setStyleSheet(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 0, 2, 1, 1)
        self.f6eu = QtGui.QSpinBox(Page06)
        self.f6eu.setEnabled(True)
        self.f6eu.setMinimumSize(QtCore.QSize(60, 20))
        self.f6eu.setMaximumSize(QtCore.QSize(60, 20))
        self.f6eu.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6eu.setWrapping(False)
        self.f6eu.setFrame(True)
        self.f6eu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6eu.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6eu.setAccelerated(False)
        self.f6eu.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6eu.setKeyboardTracking(True)
        self.f6eu.setSuffix(_fromUtf8(""))
        self.f6eu.setPrefix(_fromUtf8(""))
        self.f6eu.setMinimum(0)
        self.f6eu.setMaximum(999999)
        self.f6eu.setSingleStep(1000)
        self.f6eu.setProperty("value", 0)
        self.f6eu.setObjectName(_fromUtf8("f6eu"))
        self.gridLayout.addWidget(self.f6eu, 0, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(433, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(Page06)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(Page06)
        self.label_21.setMinimumSize(QtCore.QSize(25, 20))
        self.label_21.setMaximumSize(QtCore.QSize(25, 20))
        self.label_21.setStyleSheet(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 1, 2, 1, 1)
        self.f6ev = QtGui.QSpinBox(Page06)
        self.f6ev.setEnabled(True)
        self.f6ev.setMinimumSize(QtCore.QSize(60, 20))
        self.f6ev.setMaximumSize(QtCore.QSize(60, 20))
        self.f6ev.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6ev.setWrapping(False)
        self.f6ev.setFrame(True)
        self.f6ev.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6ev.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6ev.setAccelerated(False)
        self.f6ev.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6ev.setKeyboardTracking(True)
        self.f6ev.setSuffix(_fromUtf8(""))
        self.f6ev.setPrefix(_fromUtf8(""))
        self.f6ev.setMinimum(0)
        self.f6ev.setMaximum(999999)
        self.f6ev.setSingleStep(1000)
        self.f6ev.setProperty("value", 0)
        self.f6ev.setObjectName(_fromUtf8("f6ev"))
        self.gridLayout.addWidget(self.f6ev, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_60 = QtGui.QLabel(Page06)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout_2.addWidget(self.label_60)
        spacerItem6 = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_19 = QtGui.QLabel(Page06)
        self.label_19.setMinimumSize(QtCore.QSize(25, 20))
        self.label_19.setMaximumSize(QtCore.QSize(25, 20))
        self.label_19.setStyleSheet(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        self.f6dd = QtGui.QSpinBox(Page06)
        self.f6dd.setEnabled(True)
        self.f6dd.setMinimumSize(QtCore.QSize(60, 20))
        self.f6dd.setMaximumSize(QtCore.QSize(60, 20))
        self.f6dd.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6dd.setWrapping(False)
        self.f6dd.setFrame(True)
        self.f6dd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6dd.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6dd.setAccelerated(False)
        self.f6dd.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6dd.setKeyboardTracking(True)
        self.f6dd.setSuffix(_fromUtf8(""))
        self.f6dd.setPrefix(_fromUtf8(""))
        self.f6dd.setMinimum(0)
        self.f6dd.setMaximum(999999)
        self.f6dd.setSingleStep(1000)
        self.f6dd.setProperty("value", 0)
        self.f6dd.setObjectName(_fromUtf8("f6dd"))
        self.horizontalLayout_2.addWidget(self.f6dd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_62 = QtGui.QLabel(Page06)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_3.addWidget(self.label_62, 0, 0, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(358, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(Page06)
        self.label_8.setStyleSheet(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(Page06)
        self.label_22.setMinimumSize(QtCore.QSize(25, 20))
        self.label_22.setMaximumSize(QtCore.QSize(25, 20))
        self.label_22.setStyleSheet(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 2, 1, 1)
        self.f6cb = QtGui.QSpinBox(Page06)
        self.f6cb.setEnabled(True)
        self.f6cb.setMinimumSize(QtCore.QSize(60, 20))
        self.f6cb.setMaximumSize(QtCore.QSize(60, 20))
        self.f6cb.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6cb.setWrapping(False)
        self.f6cb.setFrame(True)
        self.f6cb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6cb.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6cb.setAccelerated(False)
        self.f6cb.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6cb.setKeyboardTracking(True)
        self.f6cb.setSuffix(_fromUtf8(""))
        self.f6cb.setPrefix(_fromUtf8(""))
        self.f6cb.setMinimum(0)
        self.f6cb.setMaximum(999999)
        self.f6cb.setSingleStep(1000)
        self.f6cb.setProperty("value", 0)
        self.f6cb.setObjectName(_fromUtf8("f6cb"))
        self.gridLayout_3.addWidget(self.f6cb, 1, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(353, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Page06)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(Page06)
        self.label_23.setMinimumSize(QtCore.QSize(25, 20))
        self.label_23.setMaximumSize(QtCore.QSize(25, 20))
        self.label_23.setStyleSheet(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 2, 2, 1, 1)
        self.f6hj = QtGui.QSpinBox(Page06)
        self.f6hj.setEnabled(True)
        self.f6hj.setMinimumSize(QtCore.QSize(60, 20))
        self.f6hj.setMaximumSize(QtCore.QSize(60, 20))
        self.f6hj.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6hj.setWrapping(False)
        self.f6hj.setFrame(True)
        self.f6hj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6hj.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6hj.setAccelerated(False)
        self.f6hj.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6hj.setKeyboardTracking(True)
        self.f6hj.setSuffix(_fromUtf8(""))
        self.f6hj.setPrefix(_fromUtf8(""))
        self.f6hj.setMinimum(0)
        self.f6hj.setMaximum(999999)
        self.f6hj.setSingleStep(1000)
        self.f6hj.setProperty("value", 0)
        self.f6hj.setObjectName(_fromUtf8("f6hj"))
        self.gridLayout_3.addWidget(self.f6hj, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_63 = QtGui.QLabel(Page06)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_3.addWidget(self.label_63)
        spacerItem9 = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_24 = QtGui.QLabel(Page06)
        self.label_24.setMinimumSize(QtCore.QSize(25, 20))
        self.label_24.setMaximumSize(QtCore.QSize(25, 20))
        self.label_24.setStyleSheet(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_3.addWidget(self.label_24)
        self.f6gh = QtGui.QSpinBox(Page06)
        self.f6gh.setEnabled(True)
        self.f6gh.setMinimumSize(QtCore.QSize(60, 20))
        self.f6gh.setMaximumSize(QtCore.QSize(60, 20))
        self.f6gh.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6gh.setWrapping(False)
        self.f6gh.setFrame(True)
        self.f6gh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6gh.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6gh.setAccelerated(False)
        self.f6gh.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6gh.setKeyboardTracking(True)
        self.f6gh.setSuffix(_fromUtf8(""))
        self.f6gh.setPrefix(_fromUtf8(""))
        self.f6gh.setMinimum(0)
        self.f6gh.setMaximum(999999)
        self.f6gh.setSingleStep(1000)
        self.f6gh.setProperty("value", 0)
        self.f6gh.setObjectName(_fromUtf8("f6gh"))
        self.horizontalLayout_3.addWidget(self.f6gh)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_64 = QtGui.QLabel(Page06)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_4.addWidget(self.label_64, 0, 0, 1, 17)
        self.label_46 = QtGui.QLabel(Page06)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_4.addWidget(self.label_46, 1, 1, 1, 1)
        self.label_47 = QtGui.QLabel(Page06)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_4.addWidget(self.label_47, 1, 4, 1, 1)
        self.label_48 = QtGui.QLabel(Page06)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_4.addWidget(self.label_48, 1, 7, 1, 1)
        self.label_49 = QtGui.QLabel(Page06)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_4.addWidget(self.label_49, 1, 10, 1, 1)
        self.label_50 = QtGui.QLabel(Page06)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_4.addWidget(self.label_50, 1, 13, 1, 1)
        self.label_51 = QtGui.QLabel(Page06)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_4.addWidget(self.label_51, 1, 16, 1, 1)
        self.label_25 = QtGui.QLabel(Page06)
        self.label_25.setMinimumSize(QtCore.QSize(25, 20))
        self.label_25.setMaximumSize(QtCore.QSize(25, 20))
        self.label_25.setStyleSheet(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 2, 0, 1, 1)
        self.f6fa = QtGui.QSpinBox(Page06)
        self.f6fa.setEnabled(True)
        self.f6fa.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fa.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fa.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fa.setWrapping(False)
        self.f6fa.setFrame(True)
        self.f6fa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fa.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fa.setAccelerated(False)
        self.f6fa.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fa.setKeyboardTracking(True)
        self.f6fa.setSuffix(_fromUtf8(""))
        self.f6fa.setPrefix(_fromUtf8(""))
        self.f6fa.setMinimum(0)
        self.f6fa.setMaximum(999999)
        self.f6fa.setSingleStep(1000)
        self.f6fa.setProperty("value", 0)
        self.f6fa.setObjectName(_fromUtf8("f6fa"))
        self.gridLayout_4.addWidget(self.f6fa, 2, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 2, 1, 1)
        self.label_26 = QtGui.QLabel(Page06)
        self.label_26.setMinimumSize(QtCore.QSize(25, 20))
        self.label_26.setMaximumSize(QtCore.QSize(25, 20))
        self.label_26.setStyleSheet(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 2, 3, 1, 1)
        self.f6fb = QtGui.QSpinBox(Page06)
        self.f6fb.setEnabled(True)
        self.f6fb.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fb.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fb.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fb.setWrapping(False)
        self.f6fb.setFrame(True)
        self.f6fb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fb.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fb.setAccelerated(False)
        self.f6fb.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fb.setKeyboardTracking(True)
        self.f6fb.setSuffix(_fromUtf8(""))
        self.f6fb.setPrefix(_fromUtf8(""))
        self.f6fb.setMinimum(0)
        self.f6fb.setMaximum(999999)
        self.f6fb.setSingleStep(1000)
        self.f6fb.setProperty("value", 0)
        self.f6fb.setObjectName(_fromUtf8("f6fb"))
        self.gridLayout_4.addWidget(self.f6fb, 2, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 5, 1, 1)
        self.label_27 = QtGui.QLabel(Page06)
        self.label_27.setMinimumSize(QtCore.QSize(25, 20))
        self.label_27.setMaximumSize(QtCore.QSize(25, 20))
        self.label_27.setStyleSheet(_fromUtf8(""))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 2, 6, 1, 1)
        self.f6fc = QtGui.QSpinBox(Page06)
        self.f6fc.setEnabled(True)
        self.f6fc.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fc.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fc.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fc.setWrapping(False)
        self.f6fc.setFrame(True)
        self.f6fc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fc.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fc.setAccelerated(False)
        self.f6fc.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fc.setKeyboardTracking(True)
        self.f6fc.setSuffix(_fromUtf8(""))
        self.f6fc.setPrefix(_fromUtf8(""))
        self.f6fc.setMinimum(0)
        self.f6fc.setMaximum(999999)
        self.f6fc.setSingleStep(1000)
        self.f6fc.setProperty("value", 0)
        self.f6fc.setObjectName(_fromUtf8("f6fc"))
        self.gridLayout_4.addWidget(self.f6fc, 2, 7, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 8, 1, 1)
        self.label_28 = QtGui.QLabel(Page06)
        self.label_28.setMinimumSize(QtCore.QSize(25, 20))
        self.label_28.setMaximumSize(QtCore.QSize(25, 20))
        self.label_28.setStyleSheet(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 2, 9, 1, 1)
        self.f6fd = QtGui.QSpinBox(Page06)
        self.f6fd.setEnabled(True)
        self.f6fd.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fd.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fd.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fd.setWrapping(False)
        self.f6fd.setFrame(True)
        self.f6fd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fd.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fd.setAccelerated(False)
        self.f6fd.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fd.setKeyboardTracking(True)
        self.f6fd.setSuffix(_fromUtf8(""))
        self.f6fd.setPrefix(_fromUtf8(""))
        self.f6fd.setMinimum(0)
        self.f6fd.setMaximum(999999)
        self.f6fd.setSingleStep(1000)
        self.f6fd.setProperty("value", 0)
        self.f6fd.setObjectName(_fromUtf8("f6fd"))
        self.gridLayout_4.addWidget(self.f6fd, 2, 10, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 2, 11, 1, 1)
        self.label_29 = QtGui.QLabel(Page06)
        self.label_29.setMinimumSize(QtCore.QSize(25, 20))
        self.label_29.setMaximumSize(QtCore.QSize(25, 20))
        self.label_29.setStyleSheet(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 2, 12, 1, 1)
        self.f6fe = QtGui.QSpinBox(Page06)
        self.f6fe.setEnabled(True)
        self.f6fe.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fe.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fe.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fe.setWrapping(False)
        self.f6fe.setFrame(True)
        self.f6fe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fe.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fe.setAccelerated(False)
        self.f6fe.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fe.setKeyboardTracking(True)
        self.f6fe.setSuffix(_fromUtf8(""))
        self.f6fe.setPrefix(_fromUtf8(""))
        self.f6fe.setMinimum(0)
        self.f6fe.setMaximum(999999)
        self.f6fe.setSingleStep(1000)
        self.f6fe.setProperty("value", 0)
        self.f6fe.setObjectName(_fromUtf8("f6fe"))
        self.gridLayout_4.addWidget(self.f6fe, 2, 13, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 2, 14, 1, 1)
        self.label_30 = QtGui.QLabel(Page06)
        self.label_30.setMinimumSize(QtCore.QSize(25, 20))
        self.label_30.setMaximumSize(QtCore.QSize(25, 20))
        self.label_30.setStyleSheet(_fromUtf8(""))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 2, 15, 1, 1)
        self.f6fl = QtGui.QSpinBox(Page06)
        self.f6fl.setEnabled(True)
        self.f6fl.setMinimumSize(QtCore.QSize(60, 20))
        self.f6fl.setMaximumSize(QtCore.QSize(60, 20))
        self.f6fl.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f6fl.setWrapping(False)
        self.f6fl.setFrame(True)
        self.f6fl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f6fl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f6fl.setAccelerated(False)
        self.f6fl.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f6fl.setKeyboardTracking(True)
        self.f6fl.setSuffix(_fromUtf8(""))
        self.f6fl.setPrefix(_fromUtf8(""))
        self.f6fl.setMinimum(0)
        self.f6fl.setMaximum(999999)
        self.f6fl.setSingleStep(1000)
        self.f6fl.setProperty("value", 0)
        self.f6fl.setObjectName(_fromUtf8("f6fl"))
        self.gridLayout_4.addWidget(self.f6fl, 2, 16, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem15 = QtGui.QSpacerItem(20, 140, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)

        self.retranslateUi(Page06)
        QtCore.QMetaObject.connectSlotsByName(Page06)
        Page06.setTabOrder(self.f6de, self.f6gj)
        Page06.setTabOrder(self.f6gj, self.f6em)
        Page06.setTabOrder(self.f6em, self.f6gp)
        Page06.setTabOrder(self.f6gp, self.f6gu)
        Page06.setTabOrder(self.f6gu, self.f6dd)

    def retranslateUi(self, Page06):
        Page06.setWindowTitle(QtGui.QApplication.translate("Page06", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Page06", "6| CHARGES DEDUCTIBLES", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setProperty("class", QtGui.QApplication.translate("Page06", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("Page06", "CSG déductible calculée sur les revenus du patrimoine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Page06", "6DE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("Page06", "Pensions alimentaires", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Page06", "Pensions alimentaires versées à des enfants majeurs :\n"
"décision de justice définitive avant 2006", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Page06", "1er enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Page06", "6GI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Page06", "2ème enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Page06", "6GJ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Page06", "Autres pensions alimentaires versées à des enfants majeurs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Page06", "1er enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Page06", "6EL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Page06", "2ème enfant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Page06", "6EM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Page06", "Autres pensions alimentaires versées : décision de justice devenue \n"
"définitive avant 2006", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Page06", "6GP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Page06", "Autres pensions alimentaires versées", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Page06", "6GU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("Page06", "Frais d\'accueil sous votre toit d\'une personne de plus de 75 ans dans le besoin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Page06", "6EU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Page06", "nombre de personnes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Page06", "6EV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("Page06", "Déductions diverses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Page06", "6DD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("Page06", "Dépenses de grosses réparations effectuées par les nus-propriétaires", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Page06", "dépenses réalisées en 2010", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Page06", "6CB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Page06", "report de dépenses de 2009", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Page06", "6HJ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("Page06", "Sommes à ajouter au revenu imposable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Page06", "6GH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("Page06", "Déficits globaux des années antérieures non encore déduits les années précédentes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setProperty("class", QtGui.QApplication.translate("Page06", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2004</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2005</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2006</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2007</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2008</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("Page06", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2009</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Page06", "6FA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Page06", "6FB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Page06", "FC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Page06", "6FD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Page06", "6FE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Page06", "6FE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setProperty("class", QtGui.QApplication.translate("Page06", "code", None, QtGui.QApplication.UnicodeUTF8))

