# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page04.ui'
#
# Created: Wed Oct 10 22:02:33 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Page04(object):
    def setupUi(self, Page04):
        Page04.setObjectName(_fromUtf8("Page04"))
        Page04.resize(730, 648)
        Page04.setMinimumSize(QtCore.QSize(730, 0))
        Page04.setMaximumSize(QtCore.QSize(730, 16777215))
        Page04.setWindowTitle(QtGui.QApplication.translate("Page04", "Form", None, QtGui.QApplication.UnicodeUTF8))
        Page04.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(Page04)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Page04)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setText(QtGui.QApplication.translate("Page04", "2| REVENUS DES VALEURS ET CAPITAUX MOBILIERS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setProperty("class", QtGui.QApplication.translate("Page04", "titreA", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(Page04)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setText(QtGui.QApplication.translate("Page04", "Revenus des actions et parts soumis au prélèvement libératoire de 18 %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(Page04)
        self.label_12.setMinimumSize(QtCore.QSize(27, 20))
        self.label_12.setMaximumSize(QtCore.QSize(27, 20))
        self.label_12.setStyleSheet(_fromUtf8(""))
        self.label_12.setText(QtGui.QApplication.translate("Page04", "2DA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setScaledContents(False)
        self.label_12.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.f2da = QtGui.QSpinBox(Page04)
        self.f2da.setEnabled(True)
        self.f2da.setMinimumSize(QtCore.QSize(60, 20))
        self.f2da.setMaximumSize(QtCore.QSize(60, 20))
        self.f2da.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2da.setWrapping(False)
        self.f2da.setFrame(True)
        self.f2da.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2da.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2da.setAccelerated(False)
        self.f2da.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2da.setKeyboardTracking(True)
        self.f2da.setSuffix(_fromUtf8(""))
        self.f2da.setPrefix(_fromUtf8(""))
        self.f2da.setMinimum(0)
        self.f2da.setMaximum(999999)
        self.f2da.setSingleStep(1000)
        self.f2da.setProperty("value", 0)
        self.f2da.setObjectName(_fromUtf8("f2da"))
        self.gridLayout.addWidget(self.f2da, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(Page04)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setText(QtGui.QApplication.translate("Page04", "Produits d’assurance-vie et de capitalisation soumis au prélèvement libératoire de 7,5 % ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(Page04)
        self.label_13.setMinimumSize(QtCore.QSize(27, 20))
        self.label_13.setMaximumSize(QtCore.QSize(27, 20))
        self.label_13.setStyleSheet(_fromUtf8(""))
        self.label_13.setText(QtGui.QApplication.translate("Page04", "2DH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.f2dh = QtGui.QSpinBox(Page04)
        self.f2dh.setEnabled(True)
        self.f2dh.setMinimumSize(QtCore.QSize(60, 20))
        self.f2dh.setMaximumSize(QtCore.QSize(60, 20))
        self.f2dh.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2dh.setWrapping(False)
        self.f2dh.setFrame(True)
        self.f2dh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2dh.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2dh.setAccelerated(False)
        self.f2dh.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2dh.setKeyboardTracking(True)
        self.f2dh.setSuffix(_fromUtf8(""))
        self.f2dh.setPrefix(_fromUtf8(""))
        self.f2dh.setMinimum(0)
        self.f2dh.setMaximum(999999)
        self.f2dh.setSingleStep(1000)
        self.f2dh.setProperty("value", 0)
        self.f2dh.setObjectName(_fromUtf8("f2dh"))
        self.gridLayout.addWidget(self.f2dh, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Page04)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setText(QtGui.QApplication.translate("Page04", "Produits de placement soumis aux prélèvements libératoires autres que ceux indiqués lignes 2DA et 2DH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(Page04)
        self.label_14.setMinimumSize(QtCore.QSize(27, 20))
        self.label_14.setMaximumSize(QtCore.QSize(27, 20))
        self.label_14.setStyleSheet(_fromUtf8(""))
        self.label_14.setText(QtGui.QApplication.translate("Page04", "2EE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setScaledContents(False)
        self.label_14.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 2, 1, 1)
        self.f2ee = QtGui.QSpinBox(Page04)
        self.f2ee.setEnabled(True)
        self.f2ee.setMinimumSize(QtCore.QSize(60, 20))
        self.f2ee.setMaximumSize(QtCore.QSize(60, 20))
        self.f2ee.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2ee.setWrapping(False)
        self.f2ee.setFrame(True)
        self.f2ee.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2ee.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2ee.setAccelerated(False)
        self.f2ee.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2ee.setKeyboardTracking(True)
        self.f2ee.setSuffix(_fromUtf8(""))
        self.f2ee.setPrefix(_fromUtf8(""))
        self.f2ee.setMinimum(0)
        self.f2ee.setMaximum(999999)
        self.f2ee.setSingleStep(1000)
        self.f2ee.setProperty("value", 0)
        self.f2ee.setObjectName(_fromUtf8("f2ee"))
        self.gridLayout.addWidget(self.f2ee, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_93 = QtGui.QLabel(Page04)
        self.label_93.setText(QtGui.QApplication.translate("Page04", "REVENUS OUVRANT DROIT À ABATTEMENT ne les déduisez pas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setProperty("class", QtGui.QApplication.translate("Page04", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.verticalLayout.addWidget(self.label_93)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(Page04)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setText(QtGui.QApplication.translate("Page04", "Revenus des actions et parts (crédit d’impôt inclus)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(Page04)
        self.label_15.setMinimumSize(QtCore.QSize(27, 20))
        self.label_15.setMaximumSize(QtCore.QSize(27, 20))
        self.label_15.setStyleSheet(_fromUtf8(""))
        self.label_15.setText(QtGui.QApplication.translate("Page04", "2DC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setScaledContents(False)
        self.label_15.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.f2dc = QtGui.QSpinBox(Page04)
        self.f2dc.setEnabled(True)
        self.f2dc.setMinimumSize(QtCore.QSize(60, 20))
        self.f2dc.setMaximumSize(QtCore.QSize(60, 20))
        self.f2dc.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2dc.setWrapping(False)
        self.f2dc.setFrame(True)
        self.f2dc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2dc.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2dc.setAccelerated(False)
        self.f2dc.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2dc.setKeyboardTracking(True)
        self.f2dc.setSuffix(_fromUtf8(""))
        self.f2dc.setPrefix(_fromUtf8(""))
        self.f2dc.setMinimum(0)
        self.f2dc.setMaximum(999999)
        self.f2dc.setSingleStep(1000)
        self.f2dc.setProperty("value", 0)
        self.f2dc.setObjectName(_fromUtf8("f2dc"))
        self.gridLayout_2.addWidget(self.f2dc, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Page04)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setText(QtGui.QApplication.translate("Page04", "Revenus imposables des titres non cotés détenus dans le PEA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(Page04)
        self.label_16.setMinimumSize(QtCore.QSize(27, 20))
        self.label_16.setMaximumSize(QtCore.QSize(27, 20))
        self.label_16.setStyleSheet(_fromUtf8(""))
        self.label_16.setText(QtGui.QApplication.translate("Page04", "2FU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setScaledContents(False)
        self.label_16.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 2, 1, 1)
        self.f2fu = QtGui.QSpinBox(Page04)
        self.f2fu.setEnabled(True)
        self.f2fu.setMinimumSize(QtCore.QSize(60, 20))
        self.f2fu.setMaximumSize(QtCore.QSize(60, 20))
        self.f2fu.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2fu.setWrapping(False)
        self.f2fu.setFrame(True)
        self.f2fu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2fu.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2fu.setAccelerated(False)
        self.f2fu.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2fu.setKeyboardTracking(True)
        self.f2fu.setSuffix(_fromUtf8(""))
        self.f2fu.setPrefix(_fromUtf8(""))
        self.f2fu.setMinimum(0)
        self.f2fu.setMaximum(999999)
        self.f2fu.setSingleStep(1000)
        self.f2fu.setProperty("value", 0)
        self.f2fu.setObjectName(_fromUtf8("f2fu"))
        self.gridLayout_2.addWidget(self.f2fu, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Page04)
        self.label_8.setStyleSheet(_fromUtf8(""))
        self.label_8.setText(QtGui.QApplication.translate("Page04", "Produits des contrats d’assurance-vie et de capitalisation d’une durée d’au moins 6 ou 8 ans", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(Page04)
        self.label_18.setMinimumSize(QtCore.QSize(27, 20))
        self.label_18.setMaximumSize(QtCore.QSize(27, 20))
        self.label_18.setStyleSheet(_fromUtf8(""))
        self.label_18.setText(QtGui.QApplication.translate("Page04", "2CH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setScaledContents(False)
        self.label_18.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.f2ch = QtGui.QSpinBox(Page04)
        self.f2ch.setEnabled(True)
        self.f2ch.setMinimumSize(QtCore.QSize(60, 20))
        self.f2ch.setMaximumSize(QtCore.QSize(60, 20))
        self.f2ch.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2ch.setWrapping(False)
        self.f2ch.setFrame(True)
        self.f2ch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2ch.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2ch.setAccelerated(False)
        self.f2ch.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2ch.setKeyboardTracking(True)
        self.f2ch.setSuffix(_fromUtf8(""))
        self.f2ch.setPrefix(_fromUtf8(""))
        self.f2ch.setMinimum(0)
        self.f2ch.setMaximum(999999)
        self.f2ch.setSingleStep(1000)
        self.f2ch.setProperty("value", 0)
        self.f2ch.setObjectName(_fromUtf8("f2ch"))
        self.gridLayout_2.addWidget(self.f2ch, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_94 = QtGui.QLabel(Page04)
        self.label_94.setText(QtGui.QApplication.translate("Page04", "REVENUS N’OUVRANT PAS DROIT À ABATTEMENT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setProperty("class", QtGui.QApplication.translate("Page04", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.verticalLayout.addWidget(self.label_94)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(Page04)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setText(QtGui.QApplication.translate("Page04", "Revenus de valeurs mobilières et distributions crédit d’impôt inclus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(Page04)
        self.label_19.setMinimumSize(QtCore.QSize(27, 20))
        self.label_19.setMaximumSize(QtCore.QSize(27, 20))
        self.label_19.setStyleSheet(_fromUtf8(""))
        self.label_19.setText(QtGui.QApplication.translate("Page04", "2TS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setScaledContents(False)
        self.label_19.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 1)
        self.f2ts = QtGui.QSpinBox(Page04)
        self.f2ts.setEnabled(True)
        self.f2ts.setMinimumSize(QtCore.QSize(60, 20))
        self.f2ts.setMaximumSize(QtCore.QSize(60, 20))
        self.f2ts.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2ts.setWrapping(False)
        self.f2ts.setFrame(True)
        self.f2ts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2ts.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2ts.setAccelerated(False)
        self.f2ts.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2ts.setKeyboardTracking(True)
        self.f2ts.setSuffix(_fromUtf8(""))
        self.f2ts.setPrefix(_fromUtf8(""))
        self.f2ts.setMinimum(0)
        self.f2ts.setMaximum(999999)
        self.f2ts.setSingleStep(1000)
        self.f2ts.setProperty("value", 0)
        self.f2ts.setObjectName(_fromUtf8("f2ts"))
        self.gridLayout_3.addWidget(self.f2ts, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(Page04)
        self.label_10.setStyleSheet(_fromUtf8(""))
        self.label_10.setText(QtGui.QApplication.translate("Page04", "Autres revenus distribués et revenus des structures soumises hors de France à un régime fiscal privilégié", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(Page04)
        self.label_20.setMinimumSize(QtCore.QSize(27, 20))
        self.label_20.setMaximumSize(QtCore.QSize(27, 20))
        self.label_20.setStyleSheet(_fromUtf8(""))
        self.label_20.setText(QtGui.QApplication.translate("Page04", "2GO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setScaledContents(False)
        self.label_20.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 1, 2, 1, 1)
        self.f2go = QtGui.QSpinBox(Page04)
        self.f2go.setEnabled(True)
        self.f2go.setMinimumSize(QtCore.QSize(60, 20))
        self.f2go.setMaximumSize(QtCore.QSize(60, 20))
        self.f2go.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2go.setWrapping(False)
        self.f2go.setFrame(True)
        self.f2go.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2go.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2go.setAccelerated(False)
        self.f2go.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2go.setKeyboardTracking(True)
        self.f2go.setSuffix(_fromUtf8(""))
        self.f2go.setPrefix(_fromUtf8(""))
        self.f2go.setMinimum(0)
        self.f2go.setMaximum(999999)
        self.f2go.setSingleStep(1000)
        self.f2go.setProperty("value", 0)
        self.f2go.setObjectName(_fromUtf8("f2go"))
        self.gridLayout_3.addWidget(self.f2go, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(Page04)
        self.label_11.setStyleSheet(_fromUtf8(""))
        self.label_11.setText(QtGui.QApplication.translate("Page04", "Intérêts et autres revenus assimilés crédit d’impôt inclus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(Page04)
        self.label_21.setMinimumSize(QtCore.QSize(27, 20))
        self.label_21.setMaximumSize(QtCore.QSize(27, 20))
        self.label_21.setStyleSheet(_fromUtf8(""))
        self.label_21.setText(QtGui.QApplication.translate("Page04", "2TR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setScaledContents(False)
        self.label_21.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 2, 2, 1, 1)
        self.f2tr = QtGui.QSpinBox(Page04)
        self.f2tr.setEnabled(True)
        self.f2tr.setMinimumSize(QtCore.QSize(60, 20))
        self.f2tr.setMaximumSize(QtCore.QSize(60, 20))
        self.f2tr.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2tr.setWrapping(False)
        self.f2tr.setFrame(True)
        self.f2tr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2tr.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2tr.setAccelerated(False)
        self.f2tr.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2tr.setKeyboardTracking(True)
        self.f2tr.setSuffix(_fromUtf8(""))
        self.f2tr.setPrefix(_fromUtf8(""))
        self.f2tr.setMinimum(0)
        self.f2tr.setMaximum(999999)
        self.f2tr.setSingleStep(1000)
        self.f2tr.setProperty("value", 0)
        self.f2tr.setObjectName(_fromUtf8("f2tr"))
        self.gridLayout_3.addWidget(self.f2tr, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label_95 = QtGui.QLabel(Page04)
        self.label_95.setText(QtGui.QApplication.translate("Page04", "AUTRES", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setProperty("titreB", _fromUtf8(""))
        self.label_95.setProperty("class", QtGui.QApplication.translate("Page04", "titreB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.verticalLayout.addWidget(self.label_95)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_26 = QtGui.QLabel(Page04)
        self.label_26.setStyleSheet(_fromUtf8(""))
        self.label_26.setText(QtGui.QApplication.translate("Page04", "Revenus des lignes 2DC, 2CH, 2TS, 2TR déjà soumis aux prélèvements sociaux sans CSG déductible", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 3)
        spacerItem9 = QtGui.QSpacerItem(88, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 3, 1, 2)
        self.label_27 = QtGui.QLabel(Page04)
        self.label_27.setMinimumSize(QtCore.QSize(27, 20))
        self.label_27.setMaximumSize(QtCore.QSize(27, 20))
        self.label_27.setStyleSheet(_fromUtf8(""))
        self.label_27.setText(QtGui.QApplication.translate("Page04", "2CG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setScaledContents(False)
        self.label_27.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 0, 5, 1, 1)
        self.f2cg = QtGui.QSpinBox(Page04)
        self.f2cg.setEnabled(True)
        self.f2cg.setMinimumSize(QtCore.QSize(60, 20))
        self.f2cg.setMaximumSize(QtCore.QSize(60, 20))
        self.f2cg.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2cg.setWrapping(False)
        self.f2cg.setFrame(True)
        self.f2cg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2cg.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2cg.setAccelerated(False)
        self.f2cg.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2cg.setKeyboardTracking(True)
        self.f2cg.setSuffix(_fromUtf8(""))
        self.f2cg.setPrefix(_fromUtf8(""))
        self.f2cg.setMinimum(0)
        self.f2cg.setMaximum(999999)
        self.f2cg.setSingleStep(1000)
        self.f2cg.setProperty("value", 0)
        self.f2cg.setObjectName(_fromUtf8("f2cg"))
        self.gridLayout_4.addWidget(self.f2cg, 0, 6, 1, 1)
        self.label_28 = QtGui.QLabel(Page04)
        self.label_28.setStyleSheet(_fromUtf8(""))
        self.label_28.setText(QtGui.QApplication.translate("Page04", "Revenus des lignes 2DC, 2CH, 2TS, 2TR déjà soumis aux prélèvements sociaux avec CSG déductible", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 1, 0, 1, 3)
        spacerItem10 = QtGui.QSpacerItem(88, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 3, 1, 2)
        self.label_29 = QtGui.QLabel(Page04)
        self.label_29.setMinimumSize(QtCore.QSize(27, 20))
        self.label_29.setMaximumSize(QtCore.QSize(27, 20))
        self.label_29.setStyleSheet(_fromUtf8(""))
        self.label_29.setText(QtGui.QApplication.translate("Page04", "2BH", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setScaledContents(False)
        self.label_29.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 1, 5, 1, 1)
        self.f2bh = QtGui.QSpinBox(Page04)
        self.f2bh.setEnabled(True)
        self.f2bh.setMinimumSize(QtCore.QSize(60, 20))
        self.f2bh.setMaximumSize(QtCore.QSize(60, 20))
        self.f2bh.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2bh.setWrapping(False)
        self.f2bh.setFrame(True)
        self.f2bh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2bh.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2bh.setAccelerated(False)
        self.f2bh.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2bh.setKeyboardTracking(True)
        self.f2bh.setSuffix(_fromUtf8(""))
        self.f2bh.setPrefix(_fromUtf8(""))
        self.f2bh.setMinimum(0)
        self.f2bh.setMaximum(999999)
        self.f2bh.setSingleStep(1000)
        self.f2bh.setProperty("value", 0)
        self.f2bh.setObjectName(_fromUtf8("f2bh"))
        self.gridLayout_4.addWidget(self.f2bh, 1, 6, 1, 1)
        self.label_24 = QtGui.QLabel(Page04)
        self.label_24.setStyleSheet(_fromUtf8(""))
        self.label_24.setText(QtGui.QApplication.translate("Page04", "Frais venant en déduction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 2, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(398, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 1, 1, 4)
        self.label_25 = QtGui.QLabel(Page04)
        self.label_25.setMinimumSize(QtCore.QSize(27, 20))
        self.label_25.setMaximumSize(QtCore.QSize(27, 20))
        self.label_25.setStyleSheet(_fromUtf8(""))
        self.label_25.setText(QtGui.QApplication.translate("Page04", "2CA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setScaledContents(False)
        self.label_25.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 2, 5, 1, 1)
        self.f2ca = QtGui.QSpinBox(Page04)
        self.f2ca.setEnabled(True)
        self.f2ca.setMinimumSize(QtCore.QSize(60, 20))
        self.f2ca.setMaximumSize(QtCore.QSize(60, 20))
        self.f2ca.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2ca.setWrapping(False)
        self.f2ca.setFrame(True)
        self.f2ca.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2ca.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2ca.setAccelerated(False)
        self.f2ca.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2ca.setKeyboardTracking(True)
        self.f2ca.setSuffix(_fromUtf8(""))
        self.f2ca.setPrefix(_fromUtf8(""))
        self.f2ca.setMinimum(0)
        self.f2ca.setMaximum(999999)
        self.f2ca.setSingleStep(1000)
        self.f2ca.setProperty("value", 0)
        self.f2ca.setObjectName(_fromUtf8("f2ca"))
        self.gridLayout_4.addWidget(self.f2ca, 2, 6, 1, 1)
        self.label_22 = QtGui.QLabel(Page04)
        self.label_22.setStyleSheet(_fromUtf8(""))
        self.label_22.setText(QtGui.QApplication.translate("Page04", "Crédits d’impôt sur valeurs étrangères", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 3, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(398, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 3, 1, 1, 4)
        self.label_23 = QtGui.QLabel(Page04)
        self.label_23.setMinimumSize(QtCore.QSize(27, 20))
        self.label_23.setMaximumSize(QtCore.QSize(27, 20))
        self.label_23.setStyleSheet(_fromUtf8(""))
        self.label_23.setText(QtGui.QApplication.translate("Page04", "2AB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setScaledContents(False)
        self.label_23.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 3, 5, 1, 1)
        self.f2ab = QtGui.QSpinBox(Page04)
        self.f2ab.setEnabled(True)
        self.f2ab.setMinimumSize(QtCore.QSize(60, 20))
        self.f2ab.setMaximumSize(QtCore.QSize(60, 20))
        self.f2ab.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2ab.setWrapping(False)
        self.f2ab.setFrame(True)
        self.f2ab.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2ab.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2ab.setAccelerated(False)
        self.f2ab.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2ab.setKeyboardTracking(True)
        self.f2ab.setSuffix(_fromUtf8(""))
        self.f2ab.setPrefix(_fromUtf8(""))
        self.f2ab.setMinimum(0)
        self.f2ab.setMaximum(999999)
        self.f2ab.setSingleStep(1000)
        self.f2ab.setProperty("value", 0)
        self.f2ab.setObjectName(_fromUtf8("f2ab"))
        self.gridLayout_4.addWidget(self.f2ab, 3, 6, 1, 1)
        self.label_34 = QtGui.QLabel(Page04)
        self.label_34.setStyleSheet(_fromUtf8(""))
        self.label_34.setText(QtGui.QApplication.translate("Page04", "Déficit des années antérieures non encore déduits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 4, 0, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(178, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 4, 2, 1, 2)
        self.label_39 = QtGui.QLabel(Page04)
        self.label_39.setStyleSheet(_fromUtf8(""))
        self.label_39.setText(QtGui.QApplication.translate("Page04", "2006", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_4.addWidget(self.label_39, 4, 4, 1, 1)
        self.label_37 = QtGui.QLabel(Page04)
        self.label_37.setMinimumSize(QtCore.QSize(27, 20))
        self.label_37.setMaximumSize(QtCore.QSize(27, 20))
        self.label_37.setStyleSheet(_fromUtf8(""))
        self.label_37.setText(QtGui.QApplication.translate("Page04", "2AA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setTextFormat(QtCore.Qt.AutoText)
        self.label_37.setScaledContents(False)
        self.label_37.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_4.addWidget(self.label_37, 4, 5, 1, 1)
        self.f2aa = QtGui.QSpinBox(Page04)
        self.f2aa.setEnabled(True)
        self.f2aa.setMinimumSize(QtCore.QSize(60, 20))
        self.f2aa.setMaximumSize(QtCore.QSize(60, 20))
        self.f2aa.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2aa.setWrapping(False)
        self.f2aa.setFrame(True)
        self.f2aa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2aa.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2aa.setAccelerated(False)
        self.f2aa.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2aa.setKeyboardTracking(True)
        self.f2aa.setSuffix(_fromUtf8(""))
        self.f2aa.setPrefix(_fromUtf8(""))
        self.f2aa.setMinimum(0)
        self.f2aa.setMaximum(999999)
        self.f2aa.setSingleStep(1000)
        self.f2aa.setProperty("value", 0)
        self.f2aa.setObjectName(_fromUtf8("f2aa"))
        self.gridLayout_4.addWidget(self.f2aa, 4, 6, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(178, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 5, 2, 1, 2)
        self.label_40 = QtGui.QLabel(Page04)
        self.label_40.setStyleSheet(_fromUtf8(""))
        self.label_40.setText(QtGui.QApplication.translate("Page04", "2007", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 5, 4, 1, 1)
        self.label_36 = QtGui.QLabel(Page04)
        self.label_36.setMinimumSize(QtCore.QSize(27, 20))
        self.label_36.setMaximumSize(QtCore.QSize(27, 20))
        self.label_36.setStyleSheet(_fromUtf8(""))
        self.label_36.setText(QtGui.QApplication.translate("Page04", "2AL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setTextFormat(QtCore.Qt.AutoText)
        self.label_36.setScaledContents(False)
        self.label_36.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_4.addWidget(self.label_36, 5, 5, 1, 1)
        self.f2al = QtGui.QSpinBox(Page04)
        self.f2al.setEnabled(True)
        self.f2al.setMinimumSize(QtCore.QSize(60, 20))
        self.f2al.setMaximumSize(QtCore.QSize(60, 20))
        self.f2al.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2al.setWrapping(False)
        self.f2al.setFrame(True)
        self.f2al.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2al.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2al.setAccelerated(False)
        self.f2al.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2al.setKeyboardTracking(True)
        self.f2al.setSuffix(_fromUtf8(""))
        self.f2al.setPrefix(_fromUtf8(""))
        self.f2al.setMinimum(0)
        self.f2al.setMaximum(999999)
        self.f2al.setSingleStep(1000)
        self.f2al.setProperty("value", 0)
        self.f2al.setObjectName(_fromUtf8("f2al"))
        self.gridLayout_4.addWidget(self.f2al, 5, 6, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(178, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 6, 2, 1, 2)
        self.label_41 = QtGui.QLabel(Page04)
        self.label_41.setStyleSheet(_fromUtf8(""))
        self.label_41.setText(QtGui.QApplication.translate("Page04", "2008", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 6, 4, 1, 1)
        self.label_35 = QtGui.QLabel(Page04)
        self.label_35.setMinimumSize(QtCore.QSize(27, 20))
        self.label_35.setMaximumSize(QtCore.QSize(27, 20))
        self.label_35.setStyleSheet(_fromUtf8(""))
        self.label_35.setText(QtGui.QApplication.translate("Page04", "2AM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setTextFormat(QtCore.Qt.AutoText)
        self.label_35.setScaledContents(False)
        self.label_35.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_4.addWidget(self.label_35, 6, 5, 2, 1)
        self.f2am = QtGui.QSpinBox(Page04)
        self.f2am.setEnabled(True)
        self.f2am.setMinimumSize(QtCore.QSize(60, 20))
        self.f2am.setMaximumSize(QtCore.QSize(60, 20))
        self.f2am.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2am.setWrapping(False)
        self.f2am.setFrame(True)
        self.f2am.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2am.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2am.setAccelerated(False)
        self.f2am.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2am.setKeyboardTracking(True)
        self.f2am.setSuffix(_fromUtf8(""))
        self.f2am.setPrefix(_fromUtf8(""))
        self.f2am.setMinimum(0)
        self.f2am.setMaximum(999999)
        self.f2am.setSingleStep(1000)
        self.f2am.setProperty("value", 0)
        self.f2am.setObjectName(_fromUtf8("f2am"))
        self.gridLayout_4.addWidget(self.f2am, 6, 6, 2, 1)
        spacerItem16 = QtGui.QSpacerItem(178, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 7, 2, 2, 2)
        self.label_42 = QtGui.QLabel(Page04)
        self.label_42.setStyleSheet(_fromUtf8(""))
        self.label_42.setText(QtGui.QApplication.translate("Page04", "2009", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 8, 4, 1, 1)
        self.label_38 = QtGui.QLabel(Page04)
        self.label_38.setMinimumSize(QtCore.QSize(27, 20))
        self.label_38.setMaximumSize(QtCore.QSize(27, 20))
        self.label_38.setStyleSheet(_fromUtf8(""))
        self.label_38.setText(QtGui.QApplication.translate("Page04", "2AN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setTextFormat(QtCore.Qt.AutoText)
        self.label_38.setScaledContents(False)
        self.label_38.setProperty("class", QtGui.QApplication.translate("Page04", "code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_4.addWidget(self.label_38, 8, 5, 1, 1)
        self.f2an = QtGui.QSpinBox(Page04)
        self.f2an.setEnabled(True)
        self.f2an.setMinimumSize(QtCore.QSize(60, 20))
        self.f2an.setMaximumSize(QtCore.QSize(60, 20))
        self.f2an.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.f2an.setWrapping(False)
        self.f2an.setFrame(True)
        self.f2an.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2an.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.f2an.setAccelerated(False)
        self.f2an.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.f2an.setKeyboardTracking(True)
        self.f2an.setSuffix(_fromUtf8(""))
        self.f2an.setPrefix(_fromUtf8(""))
        self.f2an.setMinimum(0)
        self.f2an.setMaximum(999999)
        self.f2an.setSingleStep(1000)
        self.f2an.setProperty("value", 0)
        self.f2an.setObjectName(_fromUtf8("f2an"))
        self.gridLayout_4.addWidget(self.f2an, 8, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem17)

        self.retranslateUi(Page04)
        QtCore.QMetaObject.connectSlotsByName(Page04)
        Page04.setTabOrder(self.f2da, self.f2dh)
        Page04.setTabOrder(self.f2dh, self.f2ee)
        Page04.setTabOrder(self.f2ee, self.f2dc)
        Page04.setTabOrder(self.f2dc, self.f2fu)
        Page04.setTabOrder(self.f2fu, self.f2ch)
        Page04.setTabOrder(self.f2ch, self.f2ts)
        Page04.setTabOrder(self.f2ts, self.f2go)
        Page04.setTabOrder(self.f2go, self.f2tr)
        Page04.setTabOrder(self.f2tr, self.f2cg)
        Page04.setTabOrder(self.f2cg, self.f2bh)
        Page04.setTabOrder(self.f2bh, self.f2ca)
        Page04.setTabOrder(self.f2ca, self.f2ab)
        Page04.setTabOrder(self.f2ab, self.f2aa)
        Page04.setTabOrder(self.f2aa, self.f2al)
        Page04.setTabOrder(self.f2al, self.f2am)

    def retranslateUi(self, Page04):
        pass

