###############################################################################
## File for Anaconda.org
## WARNING : strings PYPI VERSION, PYPI URL and PYPI SHA256 will be replaced
## by CI script get_pypi_info.py, leave them as is.
###############################################################################

{% set name = "OpenFisca-Core" %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: PYPI_URL
  sha256: PYPI_SHA256

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - openfisca = openfisca_core.scripts.openfisca_command:main
    - openfisca-run-test = openfisca_core.scripts.openfisca_command:main

requirements:
  host:
    - python
    - pip
  run:
    - python >= 3.7, < 4.0
    - PyYAML >= 6.0.0, < 7.0.0
    - dpath >= 2.1.0, < 3.0.0
    - importlib-metadata < 4.3.0
    - nptyping == 1.4.4
    - numexpr >= 2.8.0, <= 3.0.0
    - numpy >= 1.20, < 1.21
    - psutil >= 5.9.0, < 6.0.0
    - pytest >= 5.4.0, < 6.0.0
    - sortedcontainers == 2.2.2
    - typing-extensions >= 4.4.0, < 5.0.0

test:
  imports:
    - openfisca_core
    - openfisca_core.commons
  requires:
    - pytest >= 5.4.0, < 6.0.0
    - pip
  commands:
    - pip check
    - openfisca --help
    - openfisca-run-test --help

outputs:
  - name: openfisca-core

  - name: openfisca-core-api
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >= 3.7, < 4.0
        - markupsafe == 2.0.1
        - flask == 1.1.4
        - flask-cors == 3.0.10
        - gunicorn >= 20.1.0, < 21.0.0
        - werkzeug >= 1.0.0, < 2.0.0
        - {{ pin_subpackage('openfisca-core', exact=True) }}

  - name: openfisca-core-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >= 1.5.0, < 1.6.0
        - coverage >= 6.5.0, < 7.0.0
        - darglint == 1.8.0
        - flake8 >= 4.0.0, < 4.1.0
        - flake8-bugbear >= 19.8.0, < 20.0.0
        - flake8-docstrings == 1.6.0
        - flake8-print >= 3.1.0, < 4.0.0
        - flake8-rst-docstrings == 0.2.3
        - idna >= 3.4.0, < 4.0.0
        - isort >= 5.11.0, < 6.0.0
        - mypy == 0.910
        - openapi-spec-validator >= 0.5.0, < 0.6.0
        - pycodestyle >= 2.8.0, < 2.9.0
        - pylint == 2.10.2
        - xdoctest >= 1.1.0, < 2.0.0
        - openfisca-country-template >= 5.0.0, < 6.0.0
        - openfisca-extension-template >= 1.3.13, < 2.0.0
        - {{ pin_subpackage('openfisca-core-api', exact=True) }}

about:
  home: https://openfisca.org
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "A versatile microsimulation free software"
  doc_url: https://openfisca.org
  dev_url: https://github.com/openfisca/openfisca-core/
  description: This package contains the core features of OpenFisca, which are meant to be used by country packages such as OpenFisca-Country-Template.
