###############################################################################
## File for Anaconda.org
## WARNING : strings PYPI_VERSION, PYPI_URL, PYPI_SHA256 and PYPI_DEPS will be replaced
## by CI script get_pypi_info.py, leave them as is.
###############################################################################

{% set name = "OpenFisca-Core" %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: PYPI_URL
  sha256: PYPI_SHA256

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - openfisca = openfisca_core.scripts.openfisca_command:main
    - openfisca-run-test = openfisca_core.scripts.openfisca_command:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6,<4.0
PYPI_DEPS

test:
  imports:
    - openfisca_core
    - openfisca_core.commons
  requires:
    - pytest >=4.4.1,<6.0.0
    - pip
  commands:
    - pip check
    - openfisca --help
    - openfisca-run-test --help

outputs:
  - name: openfisca-core

  - name: openfisca-core-api
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.6,<4.0
        - flask ==1.1.2
        - flask-cors ==3.0.10
        - gunicorn >=20.0.0,<21.0.0
        - werkzeug >=1.0.0,<2.0.0
        - {{ pin_subpackage('openfisca-core', exact=True) }}

  - name: openfisca-core-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >=1.4.0,<1.6.0
        - coverage ==6.0.2
        - darglint ==1.8.0
        - flake8 >=3.9.0,<4.0.0
        - flake8-bugbear >=19.3.0,<20.0.0
        - flake8-docstrings ==1.6.0
        - flake8-print >=3.1.0,<4.0.0
        - flake8-rst-docstrings ==0.2.3
        - mypy ==0.910
        - openfisca-country-template >=3.10.0,<4.0.0
        - openfisca-extension-template >=1.2.0rc0,<2.0.0
        - pylint ==2.10.2
        - {{ pin_subpackage('openfisca-core-api', exact=True) }}

about:
  home: https://openfisca.org
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "A versatile microsimulation free software"
  doc_url: https://openfisca.org
  dev_url: https://github.com/openfisca/openfisca-core/
  description: This package contains the core features of OpenFisca, which are meant to be used by country packages such as OpenFisca-Country-Template.
