###############################################################################
## File for Anaconda.org
## It use Jinja2 templating code to retreive information from setup.py
###############################################################################

{% set name = "OpenFisca-Core" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - openfisca = openfisca_core.scripts.openfisca_command:main
    - openfisca-run-test = openfisca_core.scripts.openfisca_command:main

requirements:
  host:
    - python
    - pip
  run:
    {% for req in data.get('install_requires', []) %}
    - {{ req }}
    {% endfor %}
    # - python >=3.9,<4.0
    # - PyYAML >=6.0,<7.0
    # - dpath >=2.1.4,<3.0.0
    # - importlib-metadata >=6.1.0,<7.0
    # - numexpr >=2.8.4,<=3.0
    # - numpy >=1.24.2,<2.0
    # - psutil >=5.9.4,<6.0.0
    # - pytest >=7.2.2,<8.0.0
    # - sortedcontainers >=2.4.0
    # - typing-extensions >=4.5.0,<5.0

test:
  imports:
    - openfisca_core
    - openfisca_core.commons
  requires:
    - pip
  commands:
    - pip check
    - openfisca --help
    - openfisca-run-test --help

outputs:
  - name: openfisca-core

  - name: openfisca-core-api
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.9,<4.0
        {% for req in data.get('api_requirements', []) %}
        - {{ req }}
        {% endfor %}
        # 
        # - flask >=2.2.3,<3.0
        # - flask-cors >=3.0.10,<4.0
        # - gunicorn >=20.1.0,<21.0.0
        # - werkzeug >=2.2.3,<3.0.0
        - {{ pin_subpackage('openfisca-core', exact=True) }}

  - name: openfisca-core-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.9,<4.0
        {% for req in data.get('dev_requirements', []) %}
        - {{ req }}
        {% endfor %}
        - {{ pin_subpackage('openfisca-core-api', exact=True) }}

about:
  home: https://openfisca.org
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "A versatile microsimulation free software"
  doc_url: https://openfisca.org
  dev_url: https://github.com/openfisca/openfisca-core/
  description: This package contains the core features of OpenFisca, which are meant to be used by country packages such as OpenFisca-Country-Template.
