name: Setup package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

      activate_command:
        required: true
        type: string

jobs:
  deps:
    runs-on: ${{ inputs.os }}
    name: pip-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      # To colorize output of make tasks.
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: Use zstd for faster cache restore (windows)
      if: ${{ startsWith(inputs.os, 'windows') }}
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: venv
        key: pip-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}
        restore-keys: pip-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-

    - name: Install dependencies
      run: |
        python -m venv venv
        ${{ inputs.activate_command }}
        make install-deps install-dist
        pip install numpy==${{ inputs.numpy }}

  build:
    runs-on: ${{ inputs.os }}
    needs: [deps]
    name: pip-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: Use zstd for faster cache restore (windows)
      if: ${{ startsWith(inputs.os, 'windows') }}
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: venv
        key: pip-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: venv/**/[Oo]pen[Ff]isca*
        key: pip-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}
        restore-keys: |
          pip-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-
          pip-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-

    - name: Cache release
      uses: actions/cache@v4
      with:
        path: dist
        key: pip-release-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}

    - name: Build package
      run: |
        ${{ inputs.activate_command }}
        make install-test clean build
