name: Setup conda

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

defaults:
  run:
    shell: bash -l {0}

jobs:
  setup-conda:
    runs-on: ${{ inputs.os }}
    name: setup-conda-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      # To colorize output of make tasks.
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache conda env
      uses: actions/cache@v4
      with:
        path: |
          /usr/share/miniconda/envs/openfisca
          ~/.conda/envs/openfisca
          .env.yaml
        key: conda-env-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}
        restore-keys: conda-env-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-

    - name: Cache conda deps
      uses: actions/cache@v4
      with:
        path: |
          ~/conda_pkgs_dir
          ~/conda-cache
        key: conda-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}
        restore-keys: conda-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-
      id: cache-env

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: openfisca
        auto-update-conda: true
        channels: conda-forge
        python-version: ${{ inputs.python }}
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Update conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: openfisca
        auto-update-conda: true
        environment-file: .env.yaml
      if: steps.cache-env.outputs.cache-hit == 'true'

    - name: Install dependencies
      run: |
        conda install --name openfisca conda-build
        conda install --name openfisca numpy=${{ inputs.numpy }}
        conda install --name openfisca python=${{ inputs.python }}
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Update dependencies
      run: conda env update --name openfisca --file .env.yaml
      if: steps.cache-env.outputs.cache-hit == 'true'

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: ~/conda-bld
        key: conda-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}
        restore-keys: |
          conda-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-
          conda-build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-

    - name: Cache release
      uses: actions/cache@v4
      with:
        path: ~/conda-rel
        key: conda-release-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}

    - name: Build conda package
      run: |
        mkdir -p ~/conda-rel
        conda build \
          .conda \
          --use-local \
          --build-only \
          --croot ~/conda-bld \
          --cache-dir ~/conda-cache \
          --output-folder ~/conda-rel \
          --numpy ${{ inputs.numpy }} \
          --python ${{ inputs.python }}

    - name: Export env
      run: conda env export --name openfisca > .env.yaml
