name: Install dependencies

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

      activate_command:
        required: true
        type: string

jobs:
  deps:
    runs-on: ${{ input.os }}
    name: deps-${{ input.os }}-np${{ input.numpy }}-py${{ input.python }}
    env:
      TERM: xterm-256color  # To colorize output of make tasks.

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ input.python }}

      - name: Use zstd for faster cache restore (windows)
        if: ${{ startsWith(input.os, 'windows') }}
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - name: Cache dependencies
        id: restore-deps
        uses: actions/cache@v3
        with:
          path: venv
          key: deps-${{ input.os }}-np${{ input.numpy }}-py${{ input.python }}-${{ hashFiles('setup.py') }}
          restore-keys: deps-${{ input.os }}-np${{ input.numpy }}-py${{ input.python }}-

      - name: Install dependencies
        run: |
          python -m venv venv
          ${{ input.activate_command }}
          make install-deps install-dist
