name: Lint package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

      activate_command:
        required: true
        type: string

jobs:
  lint:
    runs-on: ${{ inputs.os }}
    name: lint-doc-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      TERM: xterm-256color  # To colorize output of make tasks.

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: Use zstd for faster cache restore (windows)
      if: ${{ startsWith(inputs.os, 'windows') }}
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: venv
        key: deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{
          hashFiles('setup.py') }}

    - name: Lint doc
      run: |
        ${{ inputs.activate_command }}
        make clean check-syntax-errors lint-doc

    - name: Lint styles
      run: |
        ${{ inputs.activate_command }}
        make clean check-syntax-errors check-style
