name: Test conda package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ inputs.os }}
    name: conda-test-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      TERM: xterm-256color  # To colorize output of make tasks.

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache conda env
      uses: actions/cache@v4
      with:
        path: |
          /usr/share/miniconda/envs/openfisca
          ~/.conda/envs/openfisca
          .env.yaml
        key: conda-env-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}

    - name: Cache conda deps
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: conda-deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}

    - name: Cache release
      uses: actions/cache@v4
      with:
        path: ~/conda-rel
        key: conda-release-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}

    - name: Update conda & dependencies
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: openfisca
        auto-update-conda: true
        environment-file: .env.yaml

    - name: Install core
      run: conda install openfisca-core-dev --channel file:///home/runner/conda-rel

    - name: Run core tests
      run: make test-core
