name: OpenFisca-Core / Pull request review

env:
  UPPER_PYTHON_VERSION: &upper_pyver 3.13.11

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, ready_for_review]
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false # Default is true but it is nice to have a shortcut here to disable it and test the full matrix
      matrix: &matrix
        resolution: [highest, lowest-direct]
        os: [ubuntu-24.04, windows-2025]
        python:
          - 3.11
          - 3.12.10
          - *upper_pyver
    runs-on: ${{ matrix.os }}
    env:
      # To colorize output of make tasks.
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: ${{ matrix.python }}

    - name: Run Openfisca Core tests in parallel
      # To evaluate that parallel mode works
      run: uv run --frozen --resolution=${{matrix.resolution}} --extra template make test-core openfisca_args="--in-parallel"

    - name: Run Country Template tests
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        uv run --frozen --resolution=${{matrix.resolution}} --extra template make test-country

    - name: Run Extension Template tests
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        uv run --frozen --resolution=${{matrix.resolution}} --extra template make test-extension

  integration:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      # To colorize output of make tasks.
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: *upper_pyver

    - name: Install the project
      run: uv sync --locked --dev

    - name: Lint
      run: uv run make lint

    - run: uv build

    - name: Test the built package
      run: uv run --frozen twine check dist/*

    - name: Check version number has been properly updated
      run: uv run ${GITHUB_WORKSPACE}/.github/is-version-number-acceptable.sh

    - name: Upload distributions as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: dist
        path: dist/