name: OpenFisca-Core / Pull request review

env:
  UPPER_PYTHON_VERSION: &upper_pyver 3.13.11

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      # To colorize output of make tasks.
      TERM: xterm-256color

    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: *upper_pyver

    - name: Test
      run: uv run --extra template make test

    - name: Lint
      run: uv run make lint

    - run: uv build

    - name: Test the built package
      run: uv run --frozen twine check dist/*

  # setup:
  #   strategy:
  #     fail-fast: true
  #     matrix: &matrix
  #       include:
  #       - os: ubuntu-24.04
  #         python: 3.10.11
  #       - os: windows-2025
  #         python: 3.10.11
  #       - os: ubuntu-24.04
  #         python: 3.12.10
  #       - os: ubuntu-24.04
  #         python: 3.12.10
  #       - os: ubuntu-24.04
  #         python: *upper_pyver
  #       - os: ubuntu-24.04
  #         python: *upper_pyver
  #       - os: windows-2025
  #         python: *upper_pyver
  #   uses: ./.github/workflows/_setup.yaml
  #   with:
  #     os: ${{ matrix.os }}
  #     python: ${{ matrix.python }}

  # test-pip:
  #   needs: [setup]
  #   strategy:
  #     fail-fast: false
  #     matrix: *matrix
  #   uses: ./.github/workflows/_test-pip.yaml
  #   with:
  #     os: ${{ matrix.os }}
  #     numpy: ${{ matrix.numpy }}
  #     python: ${{ matrix.python }}

  # lint-pip:
  #   needs: [setup-pip]
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       include:
  #       # Lint with one version from each numpy series
  #       # Need to be the same as setup-pip for cache
  #       - numpy: 1.24.2
  #         python: 3.10.11
  #       - numpy: 1.26.4
  #         python: 3.12.10
  #       - numpy: 2.3.0
  #         python: *upper_pyver
  #   uses: ./.github/workflows/_lint-pip.yaml
  #   with:
  #     os: ubuntu-24.04
  #     numpy: ${{ matrix.numpy }}
  #     python: ${{ matrix.python }}

  # check-version:
  #   needs: [test-pip, lint-pip]
  #   uses: ./.github/workflows/_version.yaml
  #   with:
  #     os: ubuntu-24.04
  #     python: *upper_pyver
